---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019-09-04 17:05
---
---@class OrderView
local OrderView = class('OrderView', function()
	local node = CLayout:create(display.size)
	node.name = 'OrderView'
	return node
end)
local MODULE_TAG = {
	PRIVATE_ORDER = 1001 ,
	PUBLISH_ORDER = 1002 ,
	TAKEAWAY_ORDER= RemindTag.ORDER ,
}
local takeawayInstance = AppFacade.GetInstance():GetManager('TakeawayManager')
function OrderView:ctor()
	self:InitUI()
end
local RES_DICT               = {
	COMMON_BTN_TAB_SELECT        = _res('ui/common/common_btn_tab_select.png'),
	COMMON_BTN_TAB_DEFAULT       = _res('ui/common/common_btn_tab_default.png'),

}
--- 初始化UI
function OrderView:InitUI()
	--关闭层
	self.kindsCellData = {
	}
	if CommonUtils.GetModuleAvailable(MODULE_SWITCH.TAKEWAY) then
		table.insert( self.kindsCellData, {text = __('下一波私有订单倒计时'), time = -1, switch = MODULE_SWITCH.TAKEWAY } )
	end
	if CommonUtils.GetModuleAvailable(MODULE_SWITCH.PUBLIC_ORDER) then
		table.insert( self.kindsCellData, {text = __('下一波公有订单倒计时'), time = -1, switch = MODULE_SWITCH.PUBLIC_ORDER  } )
	end
	local closeLayer = display.newLayer(display.cx, display.cy, { ap = display.CENTER , size = display.size , color = cc.c4b(0,0,0,100) , enable = true })
	self:addChild(closeLayer)
	-- 内容层
	local bgSize = cc.size(555,display.height)
	local bgLayer = display.newLayer(display.width , bgSize.height/2 , {size = bgSize , ap = display.RIGHT_CENTER  })
	self:addChild(bgLayer,2)
	bgLayer:setPosition(cc.p(display.width+ 555, display.height/2))
	-- 吞噬层
	local swalowLayer =display.newButton(bgSize.width /2 , bgSize.height/2 , {size = bgSize , ap = display.CENTER , enable = true })
	bgLayer:addChild(swalowLayer)
	-- 背景图片
	local bgImage = display.newImageView(_res('ui/common/common_bg_4.png') , 0 , bgSize.height/2 , {scale9 = true , size = cc.size(bgSize.width + display.SAFE_L, bgSize.height), ap = display.LEFT_CENTER})
	bgLayer:addChild(bgImage)


	local modulesBtn = {}
	local height = bgSize.height - 63
	local distanceW = 160
	local moduleTable = {
		{text = __('私有订单') , tag = MODULE_TAG.PRIVATE_ORDER , pos = cc.p(bgSize.width/2 -distanceW , height ) },
		{text = __('公有订单') , tag = MODULE_TAG.PUBLISH_ORDER ,pos = cc.p(bgSize.width/2 ,  height )},
		{text = __('车库') , tag = MODULE_TAG.TAKEAWAY_ORDER ,pos = cc.p(bgSize.width/2 + distanceW ,  height )}
	}
	for i = 1 , #moduleTable do
		local data =  moduleTable[i]
		local commonGoodsBtn = display.newButton(data.pos.x , data.pos.y , { ap = display.CENTER_BOTTOM, n = RES_DICT.COMMON_BTN_TAB_DEFAULT, d = RES_DICT.COMMON_BTN_TAB_SELECT, s = RES_DICT.COMMON_BTN_TAB_DEFAULT, scale9 = true, size = cc.size(140, 48), tag = 375 })
		display.commonLabelParams(commonGoodsBtn, { text = data.text, fontSize = 24, color = '#ffffff' })
		commonGoodsBtn:setTag(data.tag)
		modulesBtn[tostring(data.tag)] = commonGoodsBtn
		bgLayer:addChild(commonGoodsBtn,10)
	end

	self.viewData = {
		bgLayer = bgLayer ,
		closeLayer = closeLayer ,
		modulesBtn = modulesBtn ,
		swalowLayer = swalowLayer
	}
end

return  OrderView
