---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019-09-04 17:05
---
---@class PrivateOrderView
local PrivateOrderView = class('PrivateOrderView', function()
	local node =  display.newLayer(0, 0, { size = cc.size(555,display.height)})
	--CLayout:create(cc.size(555,display.height))
	node.name = 'PrivateOrderView'
	return node
end)
function PrivateOrderView:ctor()
	self:InitUI()
end
--- 初始化UI
function PrivateOrderView:InitUI()
	local bgSize = cc.size(555,display.height)
	self:setAnchorPoint(display.LEFT_BOTTOM)
	self:setPosition(0,0)
	local chestHight = 0
	if app:RetrieveMediator("OrderChestMediator") then
		chestHight = 35
	end
	local cgrideCellSize = cc.size( 550, 157)
	local gridView      = CGridView:create(cc.size(550, bgSize.height - 150-chestHight))
	gridView:setColumns(1)
	gridView:setAutoRelocate(true)
	gridView:setSizeOfCell(cgrideCellSize)
	gridView:setAnchorPoint(display.LEFT_BOTTOM)
	--gridView:setCascadeOpacityEnabled(true)
	gridView:setPosition(10,10)
	self:addChild(gridView)
	local cellSize = cc.size(553,81)
	local timeLayout = display.newLayer(bgSize.width/2 , bgSize.height - 60, {ap = display.CENTER_TOP , size = cellSize})
	local countdownLineImage = display.newImageView(_res("ui/home/carexplore/order_ico_countdown_line.png") ,cellSize.width/2 , cellSize.height/2 )
	countdownLineImage:setScaleY(-1)
	self:addChild(timeLayout)
	timeLayout:addChild(countdownLineImage)
	local descrLabel  = display.newLabel(cellSize.width/2 ,cellSize.height /2 ,fontWithColor('6', { ap = display.CENTER_BOTTOM ,  text = __('下一波私有订单倒计时')}) )
	descrLabel:setName("descrLabel")
	timeLayout:addChild(descrLabel)
	-- 倒计时内容
	local countDownImage = display.newButton(cellSize.width/2 ,cellSize.height /2 ,{ ap = display.CENTER_TOP  , n = _res('ui/home/nmain/main_sandglas_bg_time.png') ,enable = false})
	display.commonLabelParams(countDownImage, fontWithColor("14", { fontSize = 22 ,  text = "00:00:00"}))
	timeLayout:addChild(countDownImage)
	self.viewData = {
		gridView = gridView ,
		descrLabel = descrLabel ,
		countDownImage = countDownImage
	}
end

function PrivateOrderView:CreateLFuturesEmpty()
	local  lrightLayout = display.newLayer(10, 0 , {size = cc.size(550, display.height - 150)})
	self:addChild(lrightLayout)
	local image = display.newImageView(_res('ui/common/common_ico_cartoon_5.png') ,550/2 , (display.height - 150)/2  )
	lrightLayout:addChild(image)
	local label  = display.newLabel(550/2 , (display.height - 150)/2 +  200   , {fontSize = 22, color = "#515151" , text = __('暂无私有外卖订单')})
	lrightLayout:addChild(label)
	self.viewData.lrightLayout = lrightLayout
end


function PrivateOrderView:UpdateTimeLabel(seconds)
	if seconds < 0  then
		self.viewData.countDownImage:setVisible(false)
		display.commonLabelParams(self.viewData.descrLabel , {text = __('暂无私有订单刷新时间') })
	else
		self.viewData.countDownImage:setVisible(true)
		display.commonLabelParams(self.viewData.descrLabel , {text = __('下一波私有订单倒计时') })
		display.commonLabelParams(self.viewData.countDownImage, {text = string.formattedTime(seconds , "%02i:%02i:%02i")})
	end
end
return  PrivateOrderView
