---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 28/02/2018 2:41 PM
---
local GameScene = require( 'Frame.GameScene' )
---@type TastingTourManager
local tastingTourMgr = AppFacade.GetInstance():GetManager("TastingTourManager")
---@class TastingTourChooseRecipeView :GameScene
local TastingTourChooseRecipeView = class('TastingTourChooseRecipeView', GameScene)
function TastingTourChooseRecipeView:ctor(params)
    self.super.ctor(self,'home.TastingTourChooseRecipeView')
    params = params or {}
    self.stageId = params.stageId or 1
    self:InitUI()
end

local BUTTON_CLICK = {
    MAKE_RECIPE_BTN   = 1001, -- 制作菜品
    SUBMIT_RECIPE_BTN = 1002, -- 提交菜品
    BACK_BTN          = 1003 , --返回关闭按钮
    ATTR_BTN          = 1004 , --属性按钮选择
}
--==============================--
--desc:初始化界面
--time:2017-08-01 03:13:56
--@return
--==============================--
function TastingTourChooseRecipeView:InitUI()
    local swallowLayer = display.newLayer(0,0,{ ap = display.CENTER , color = cc.c4b(0,0,0,150) , enable =  true})
    swallowLayer:setPosition(display.center)
    self:addChild(swallowLayer)

    local bgSize = cc.size(1120,650)
    local bgLayout = display.newLayer(display.width/2 , display.height/2, { ap = display.CENTER  , size =bgSize })
    self:addChild(bgLayout)

    -- 顶部的图片
    local topImage = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_target_bg"))
    local topSize = topImage:getContentSize()
    local topLayer = display.newLayer(bgSize.width/2 , bgSize.height ,
      {ap = display.CENTER_TOP , size = topSize })
    topImage:setPosition(cc.p(topSize.width/2 , topSize.height/2))
    topLayer:addChild(topImage)
    bgLayout:addChild(topLayer)
    local height = 1
    local requirementsTablePos = {

        cc.p(290,topSize.height - 35+ 2 + height),
        cc.p(290,topSize.height - 75 + 2+ height),
        cc.p(290,topSize.height - 115 + 2 + height)
    }
    local tagTextTable = {
        __('分类要求'),

        __('属性要求'),

        __('食材要求')
    }
    local requirementsTable = {}
    for i =1 , #requirementsTablePos do
        local pos = requirementsTablePos[i]
        local tagBg = display.newImageView(_res('ui/tastingTour/lobby/fishtravel_submit_target_bg_2'),pos.x ,pos.y,{ap = display.LEFT_CENTER}  )
        topLayer:addChild(tagBg)

        local tagBgSize  = tagBg:getContentSize()
        local tagLabel = display.newLabel(79 + 100 , tagBgSize.height/2, {fontSize = 24 , color = '#9e2900' , text = tagTextTable[i],ap = display.RIGHT_CENTER , reqW = 200   })
        tagBg:addChild(tagLabel)

        local label = display.newLabel(210,tagBgSize.height/2  ,fontWithColor('10',{fontSize = 24 ,  text = "",ap = display.LEFT_CENTER}))
        tagBg:addChild(label)

        requirementsTable[#requirementsTable+1] = label

    end
    -- 小人
    local smallPeople = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_npc"),45, 10 , {ap = display.LEFT_BOTTOM} )
    topLayer:addChild(smallPeople,2)

    local leftImage = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_bg_channel"))
    local leftImageSize = leftImage:getContentSize()
    -- 左侧的layout
    local leftLayout = display.newLayer(-20 , bgSize.height - topSize.height -5 , {ap = display.LEFT_TOP , size = leftImageSize   })
    bgLayout:addChild(leftLayout)
    leftImage:setPosition(cc.p(leftImageSize.width/2 , leftImageSize.height/2))
    leftLayout:addChild(leftImage)
    --向下图片
    local imgDown = display.newImageView(_res('ui/union/lobby/guild_img_down.png')
    ,leftImageSize.width/2 , 0, {ap = display.CENTER_BOTTOM})
    leftLayout:addChild(imgDown)
    -- 上部图片
    local imgUp = display.newImageView(_res('ui/union/lobby/guild_img_up.png')
    ,leftImageSize.width/2 , leftImageSize.height, {ap = display.CENTER_TOP})
    leftLayout:addChild(imgUp)
    local tableName =  tastingTourMgr:GetConfigDataByName(tastingTourMgr:GetConfigParse().TYPE.MENU_TAG)
    tableName = clone(tableName)
    tableName["0"] = {
        id = 0 ,
        name = __('全部'),
    }
    local count =  table.nums(tableName)
    local kindSize = cc.size(191, 80 )

    local stageOneConfig =   tastingTourMgr:GetConfigDataByName(tastingTourMgr:GetConfigParse().TYPE.STAGE)[tostring(self.stageId)] or {}
    local hideTable = stageOneConfig.hideTypeId or {}
    local ownCount =  ( table.nums(tableName) - table.nums(hideTable))

    local recipeKindLayout =   display.newLayer(leftImageSize.width/2 , leftImageSize.height -15 ,
            {size = cc.size(kindSize.width , kindSize.height  * ownCount) ,ap = display.CENTER_TOP })

    local buttonTable = {}
    for i = 0 ,count - 1   do
        local isHide = false
        for k, v in pairs(hideTable) do
            if  checkint(i) == checkint(v) then
                isHide = true
                break
            end
        end
        if not  isHide then
            local v = tableName[tostring(i)]
            local name =  v.name
            local height =(  ownCount - 0.5) *  kindSize.height
            local width = kindSize.width /2
            local button = display.newButton(width, height , {n = _res('ui/union/lobby/guild_btn_channel_default.png') , enable = true })
            recipeKindLayout:addChild(button)
            button:setTag(checkint(v.id))
            display.commonLabelParams(button,  {text = name,font = TTF_GAME_FONT, ttf = true, fontSize = 22 , hAlign = display.TAC , w = 180, color = "#7a3321" })
            buttonTable[tostring(v.id)] = button
            ownCount = ownCount - 1
        end
    end
    local bossIntroduceList = CListView:create(cc.size(kindSize.width , 470 ))
    bossIntroduceList:setDirection(eScrollViewDirectionVertical)
    bossIntroduceList:setAnchorPoint(display.CENTER_TOP)
    bossIntroduceList:setPosition(cc.p(leftImageSize.width/2 , leftImageSize.height -15))
    leftLayout:addChild(bossIntroduceList)
    bossIntroduceList:insertNodeAtLast(recipeKindLayout)
    bossIntroduceList:reloadData()
    -- bottomLayout 下面的Image
    local bottomImage = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_bg"))
    local bottomSize= bottomImage:getContentSize()
    local bottomLayout  = display.newLayer(bgSize.width +5 , bgSize.height -  topSize.height ,{
        ap = display.RIGHT_TOP , size =  bottomSize
    } )
    bottomImage:setPosition(cc.p(bottomSize.width/2 , bottomSize.height/2))
    bottomLayout:addChild(bottomImage)
    bgLayout:addChild(bottomLayout)


    -- 下面最左侧的layout
    local bottomLeftSize  = cc.size( 492, 490)
    local bottomLeftLayout =  display.newLayer(10,bottomSize.height -10,{
        ap = display.LEFT_TOP , size =  bottomLeftSize
    } )
    bottomLayout:addChild(bottomLeftLayout)
    local gridSzie =cc.size( 492, 490)
    local gradCellSize = cc.size(164, 194)
    local gridView = CGridView:create(gridSzie)
    gridView:setSizeOfCell(gradCellSize)
    gridView:setName("gridView")
    gridView:setColumns(3)
    gridView:setAutoRelocate(true)
    gridView:setAnchorPoint(display.CENTER)
    gridView:setPosition(cc.p(bottomLeftSize.width/2 , bottomLeftSize.height/2))
    bottomLeftLayout:addChild(gridView)
    -- 按照属性选择的layout
    local submitImage  = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_tab_bg"))
    local submitImageSize = submitImage:getContentSize()
    local submitTabLayout = display.newLayer(bottomLeftSize.width/2 , 0, {ap = display.CENTER_BOTTOM, size = submitImageSize})
    bottomLeftLayout:addChild(submitTabLayout)
    submitTabLayout:addChild(submitImage)
    submitImage:setPosition(cc.p(submitImageSize.width/2+2, submitImageSize.height/2))

    local kindBtn = display.newButton(130, 28 , { n =  _res("ui/tastingTour/lobby/fishtravel_submit_btn_tab") , scale9 = true , size = cc.size(250,45)})
    submitTabLayout:addChild(kindBtn)
    kindBtn:setTag(BUTTON_CLICK.ATTR_BTN)
    display.commonLabelParams(kindBtn , {fontSize = 22 , text = __('选择排序')})

    local attributebgImage = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_attribute_bg"))
    local attributebgImageSize = attributebgImage:getContentSize()
    local attrLayout = display.newLayer(bottomSize.width -8 , bottomSize.height -8  ,
                    {  ap = display.RIGHT_TOP , size = attributebgImageSize })
    attributebgImage:setPosition(cc.p(attributebgImageSize.width/2 , attributebgImageSize.height/2))
    attrLayout:addChild(attributebgImage)
    bottomLayout:addChild(attrLayout)
    local recipeSize = cc.size(166, 184)

    local recipeLayout = display.newLayer(100, attributebgImageSize.height +20 ,
                  {ap =display.CENTER_TOP , size = recipeSize})

    local logoImage = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_foods_logo"),
       recipeSize.width/2, recipeSize.height/2)
    recipeLayout:addChild(logoImage)
    -- 菜谱的图片
    local recipeImage = FilteredSpriteWithOne:create(CommonUtils.GetGoodsIconPathById("220001"))
    recipeImage:setPosition(cc.p(recipeSize.width/2, recipeSize.height/2-10))
    recipeLayout:addChild(recipeImage)
    attrLayout:addChild(recipeLayout)


    local labelTables ={
        { attrName =  __('味道:') , name = "taste" },
        { attrName =  __('口感:') , name = "museFeel"},
        { attrName =  __('香味:') , name = "fragrance" },
        { attrName =  __('外观:') , name = "exterior" }
    }
    local attrCellSize = cc.size(170, 36)
    local attrRcipeLayout = display.newLayer(189, attributebgImageSize.height - 35 ,
        {ap = display.LEFT_TOP, size = cc.size(attrCellSize.width , attrCellSize.height * #labelTables)})
    attrLayout:addChild(attrRcipeLayout)
    local attrRecipeTable = {}
    local count = #labelTables
    for k ,v in pairs(labelTables) do
        local button = display.newButton(0,(count - 0.5 ) * attrCellSize.height ,
         {n = _res("ui/tastingTour/lobby/fishtravel_submit_bg_attribute_number") , ap = display.LEFT_CENTER , enable = false } )
        attrRecipeTable[v.name] = button
        local color =  "#cf5024"
        --if k ==1 then
        --    color =  "#952700"
        --end
        local attrLabel = display.newLabel(10,attrCellSize.height/2 -2 , {ap = display.LEFT_CENTER, fontSize = 22 , color  = color , text =  v.attrName , reqW= 110 } )
        button:addChild(attrLabel)

        display.commonLabelParams(button , {offset = cc.p(30, -2), ap = display.LEFT_CENTER,color = color , fontSize = 22,  text = 60})

        attrRcipeLayout:addChild(button)
        count = count -1
    end

    -- 菜谱的名称
    local recipeName = display.newLabel(recipeSize.width/2 , recipeSize.height/2 - 90 ,
                                        {text = '土豆丝',font = TTF_GAME_FONT, ttf = true,color = "#8e5e3a", fontSize = 22})
    recipeLayout:addChild(recipeName)


    local wordImage = display.newImageView(_res('ui/tastingTour/lobby/fishtravel_submit_bg_describe') ,
    attributebgImageSize.width/2 , attributebgImageSize.height - 208 , {ap = display.CENTER_TOP})
    attrLayout:addChild(wordImage)
    local wordImageSize = wordImage:getContentSize()
    local recipeDescr = display.newLabel(wordImageSize.width/2, wordImageSize.height-20,
         fontWithColor('6',{ text= ""  , w = 280 ,ap =display.CENTER_TOP }))
    wordImage:addChild(recipeDescr)
    -- 制作菜品
    local makeBtn  = display.newButton(attributebgImageSize.width/2 - 95 , 45,{ n = _res('ui/common/common_btn_white_default') , scale9 =true })
    attrLayout:addChild(makeBtn  )
    display.commonLabelParams(makeBtn , fontWithColor('14',{text = __('制作')}))
    makeBtn:setTag(BUTTON_CLICK.MAKE_RECIPE_BTN)
    -- 提交菜品
    local submitBtn = display.newButton(attributebgImageSize.width/2 + 95 , 45,{ n = _res('ui/common/common_btn_orange')})
    attrLayout:addChild(submitBtn )
    submitBtn:setTag(BUTTON_CLICK.SUBMIT_RECIPE_BTN)
    display.commonLabelParams(submitBtn, fontWithColor('14',{text = __('提交')}))
    local backBtn = display.newButton(0, 0, {n = _res("ui/common/common_btn_back")})
    backBtn:setPosition(cc.p(display.SAFE_L + backBtn:getContentSize().width * 0.5 + 30, display.height - 53))
    self:addChild(backBtn, 5)
    backBtn:setTag(BUTTON_CLICK.BACK_BTN)


    self.viewData = {
        -- 顶部需要更新的内容
        requirementsTable = requirementsTable ,
        ------------------左侧所需的更新内容-------------
        buttonTable = buttonTable , 

        ----------------------菜谱属性 所需的更新内容-------------
        makeBtn =   makeBtn ,
        submitBtn = submitBtn ,
        recipeDescr = recipeDescr ,
        recipeName = recipeName ,
        attrRecipeTable = attrRecipeTable ,
        recipeImage  = recipeImage ,
        backBtn = backBtn ,
        attrLayout = attrLayout ,
        -------------------中部菜谱的选择 -----------------------
        kindBtn = kindBtn ,
        gridView = gridView ,
        topLayer = topLayer ,
        leftLayout = leftLayout ,
        bottomLayout = bottomLayout ,
    }
end
--[[
    创建属性选择界面
--]]
function TastingTourChooseRecipeView:CreateSelectAtttrView(sender , index)
    -- 排序类型
    local  screenType = {
        ["0"] = __('全部') ,
        ["1"] = __('味道') ,
        ["2"] = __('口感') ,
        ["3"] = __('香味') ,
        ["4"] = __('外观')
    }
    local count = table.nums(screenType)
    local cellSize = cc.size(126,56)
    local listSize = cc.size(126 , 56 * count  )
    local contentSize = cc.size(160,  listSize.height + 12 )
    local listView = CListView:create(listSize)
    listView:setBounceable(false)
    listView:setDirection(eScrollViewDirectionVertical)
    listView:setPosition(cc.p(contentSize.width/2, contentSize.height/2 +2))
    -- 内容的layer
    local contentLayer  =  display.newLayer(display.width/2 , display.height/2 , { ap = display.CENTER , size = contentSize})
    contentLayer:setPosition(display.width/2 , display.height/2)
    contentLayer:addChild(listView,2)
    local contentImage = display.newImageView(_res('ui/common/tujian_selection_frame_1.png'),contentSize.width/2 , contentSize.height/2
    ,{scale9 = true,size = contentSize})
    contentLayer:addChild(contentImage)

    for i = 0 ,  table.nums(screenType) - 1 do
        local  k = i
        local v = screenType[tostring(k)]
        count = count -1
        local cellLayout =  display.newLayer(0,0,{size = cellSize  })
        local button  =  display.newButton(cellSize.width/2 , cellSize.height/2 , {n = _res('ui/common/tujian_selection_select_btn_filter_selected.png')})
        button:setTag(checkint(k))
        cellLayout:addChild(button)
        button:setName("button")
        if i == index then
            button:setOpacity(255)
        else
            button:setOpacity(0)
        end
        if count > 0 then
            local lineImage = display.newImageView(_res('ui/common/tujian_selection_line.png') , cellSize.width/2 , 0 , {ap = display.CENTER})
            cellLayout:addChild(lineImage)
        end

        local textLabel = display.newLabel(cellSize.width/2 , cellSize.height/2 , fontWithColor('10', { text = v }))
        cellLayout:addChild(textLabel)
        listView:insertNodeAtLast(cellLayout)
    end
    listView:reloadData()
    local selectView = display.newLayer(display.cx, display.cy , {ap = display.CENTER })
    self:addChild(selectView)
    --关闭选择界面
    local closeSelectView = display.newLayer(display.cx, display.cy , {ap = display.CENTER , color =cc.c4b(0,0,0,0) , enable = true })
    selectView:addChild(closeSelectView )

    local pos = cc.p( sender:getPosition())
    closeSelectView:setPosition(display.center)
    local worldPos =  sender:getParent():convertToWorldSpace(pos)
    local noePos = closeSelectView:convertToNodeSpace(worldPos)
    contentLayer:setAnchorPoint(display.CENTER_BOTTOM)
    selectView:addChild(contentLayer)
    contentLayer:setPosition(noePos.x , noePos.y +20)
    contentLayer:setScaleY(0)
    contentLayer:setOpacity(0)
    contentLayer:runAction(cc.EaseSineOut:create(
        cc.Spawn:create(
            cc.ScaleTo:create(0.2,1) ,
            cc.FadeIn:create(0.2)
        )
    ) )
    selectView.contentLayer = contentLayer
    selectView.closeSelectView = closeSelectView
    selectView.listView     = listView
    selectView.selectView   = selectView
    return selectView
end

function TastingTourChooseRecipeView:CreateGridCell()
    local gridViewCell = CGridViewCell:new()
    local gradCellSize = cc.size(164, 194)
    gridViewCell:setContentSize()
    local bgImage =  FilteredSpriteWithOne:create(_res('ui/tastingTour/lobby/fishtravel_submit_foods_bg_default') )
    local bgSize  = bgImage:getContentSize()

    local bgImageBottom =  FilteredSpriteWithOne:create(_res('ui/tastingTour/lobby/fishtravel_submit_foods_bg_default') , cc.rect(0,153,bgSize.width , 30 ) )
    bgImage:addChild(bgImageBottom)
    bgImageBottom:setAnchorPoint(display.CENTER_BOTTOM)
    bgImageBottom:setPosition(bgSize.width/2 ,30 )
    local bgSize  = bgImage:getContentSize()
    local bgLayout = display.newLayer(gradCellSize.width/2 , gradCellSize.height/2 ,
    {ap = display.CENTER, size = bgSize , color = cc.c4b(0,0,0,0) , enable = true })
    bgImage:setPosition(cc.p(bgSize.width/2 , bgSize.height/2))
    bgLayout:addChild(bgImage)
    gridViewCell:addChild(bgLayout)
    -- 光圈
    local lightCircle = display.newImageView(_res("ui/tastingTour/lobby/fishtravel_submit_task_btn_select"),
                         bgSize.width/2 , bgSize.height/2)
    bgLayout:addChild(lightCircle)
    lightCircle:setVisible(false)

    local recipeImage = FilteredSpriteWithOne:create(CommonUtils.GetGoodsIconPathById("220001"))
    recipeImage:setPosition(cc.p(bgSize.width/2, bgSize.height/2 + 20))
    --display.newImageView(CommonUtils.GetGoodsIconPathById("220001"),
    --                                        bgSize.width/2, bgSize.height/2 + 20)
    bgLayout:addChild(recipeImage)
    recipeImage:setScale(0.9)
    local recipeNameLabel = display.newLabel(bgSize.width/2 , 30,
      fontWithColor('16',{ fontSize = 20 ,  ap = display.CENTER ,text = "" }))
    bgLayout:addChild(recipeNameLabel)

    gridViewCell.recipeImage = recipeImage
    gridViewCell.bgImageBottom = bgImageBottom
    gridViewCell.bgLayout = bgLayout
    gridViewCell.bgImage = bgImage
    gridViewCell.lightCircle = lightCircle
    gridViewCell.recipeNameLabel = recipeNameLabel
    return gridViewCell

end
--[[
    更新 CGridViewCell 的信息
--]]
function TastingTourChooseRecipeView:UpdateGridCell(cell , data, isSelected)
    local goodsId = data.recipeId -- 菜谱的id

    local recipeConfig = CommonUtils.GetConfig("goods",'goods',goodsId ) or {}
    local name = tostring(recipeConfig.name)          -- 菜谱的名称
    local recipeTexture = CommonUtils.GetGoodsIconPathById(goodsId)
    cell.recipeImage:setTexture(recipeTexture)
    display.commonLabelParams(cell.recipeNameLabel, {text = name  , w = 150 ,hAlign = display.TAC })
    -- 判断这道菜是否被选中
    if isSelected then
        cell.lightCircle:setVisible(true )
        cell.bgImage:setTexture(_res('ui/tastingTour/lobby/fishtravel_submit_foods_bg_select'))
    else
        cell.lightCircle:setVisible(false  )
        cell.bgImage:setTexture(_res('ui/tastingTour/lobby/fishtravel_submit_foods_bg_default'))
    end
end


return TastingTourChooseRecipeView
