local podTable = {
    po = {
        [__("Tips：每次击退了本章节的小丑后，章节内的关卡点都会刷新重置。")]             = __('每次击退了本章节的哈吉斯后，章节内的关卡点都会刷新重置。'),
        [__("游乐园很有趣的哦！\n别担心，我会一直在你身边保护你，所以一起来玩吧！")]       = __('旧日血案重现的教堂，亟待揭开真相。'),
        [__("每个章节小丑伤害排行榜前%s名可获得：")]                                  = __('每个章节哈吉斯伤害排行榜前%s名可获得：'),
        [__("扭蛋机")]                                                           = __('糖果机'),
        [__("在游乐园中战斗可获得的点数。击退小丑时，根据造成的伤害可以获得更多的点数哦。")] = __('在塞罗镇中进行战斗可获得的点数。击退哈吉斯时，根据造成的伤害可以获得更多的点数哦。'),
        [__("恐怖游乐园")]                                                        = __('无人知晓'),
        [__("马戏团")]                                                           = __('废墟法阵'),
        [__("拥有引路灯: %s")]                                                    = __('拥有调查报告: %s'),
        [__("乐园排行榜")]                                                        = __('塞罗镇排行榜'),
        [__("小丑伤害排行")]                                                      = __('哈吉斯伤害排行'),
        [__("本关卡无三星过关条件")]                                               = __('本关卡无三星过关条件'),
        [__("普通扭蛋")]                                                         = __('日常糖果机'),
        [__("游乐园点数")]                                                       = __('塞罗镇点数'),
        [__("累计扭蛋奖励")]                                                      = __('累计投币次数奖励'),
        [__("扭10次")]                                                          = __('投币10次'),
        [__("扭1次")]                                                           = __('投币1次'),
        [__("您还没有参与游乐园的活动哦~")]                                         = __('您还没有参与塞罗镇的活动哦'),
        [__("今日蛋池")]                                                         = __('今日糖果机'),
        [__("扭蛋上新")]                                                         = __('糖果机上新'),
        [__("排行榜每小时更新一次排名")]                                           = __('排行榜每小时更新一次排名'),
        [__("特典扭蛋预告")]                                                     = __('特典预告'),
        [__("消耗1个引路灯直接找到小丑")]                                          = __('消耗1个调查报告直接找到哈吉斯'),
        [__("剩余扭蛋")]                                                        = __('剩余投币次数'),
        [__("进入游乐园")]                                                       = __('进入塞罗镇'),
        [__("今日特典扭蛋")]                                                     = __('今日特典'),
        [__("乐园游玩奖励")]                                                     = __('塞罗镇调查奖励'),
        [__("累计完成小丑关卡奖励")]                                              = __('累计完成哈吉斯关卡奖励'),
        [__('完成小丑关卡%s次可获得')]                                            = __('完成哈吉斯关卡%s次可获得'),
        [__("完成本关卡，根据所造成的伤害折算成游乐园点数，每1000点伤害为1点游乐园点数，不满1000不会计入。")] = __('完成本关卡，根据所造成的伤害折算成塞罗镇点数，每1000点伤害为1点塞罗镇点数，不满1000不会计入。'),
        [__("完成本关卡，可获得500点游乐园点数。")]                                 = __('完成本关卡，可获得500点塞罗镇点数。'),
        [__("剩余扭蛋不足")]                                                     = __('剩余投币次数不足'),
        [__("堕神诱饵")]                                                        = __('案件证物'),
        [__("引出小丑")]                                                        = __('引出哈吉斯'),
        [__("小丑出现了!")]                                                     = __('哈吉斯出现了'),
        [__('镜子迷宫第1名')]                                                   = __('塞罗镇前10名'),
        [__('旋转茶杯第1名')]                                                   = __('糖果店前10名'),
        [__('矿道飞车第1名')]                                                   = __('治安署前10名'),
        [__('鬼屋第1名')]                                                      = __('安布利教堂前10名'),
        [__('马戏团第1名')]                                                     = __('废墟法阵前10名'),
        [__('在镜子迷宫内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在塞罗镇内对哈吉斯的单次伤害最高的玩家可以获得。'),
        [__('在旋转茶杯内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在糖果店内对哈吉斯的单次伤害最高的玩家可以获得。'),
        [__('在矿道飞车内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在治安署内对哈吉斯的单次伤害最高的玩家可以获得。'),
        [__('在鬼屋内对小丑的单次伤害最高的玩家可以获得。')]                         = __('在安布利教堂内对哈吉斯的单次伤害最高的玩家可以获得。'),
        [__('在马戏团内对小丑的单次伤害最高的玩家可以获得。')]                       = __('在废墟法阵内对哈吉斯的单次伤害最高的玩家可以获得。'),
        [__('第1名的额外奖励: ')]                                               = __('前10名的额外奖励: '),
    },
    firstMapNodePostions = {
        {
            location = {x = 1130, y = 570}
        },
        {
            location = {x = 885, y = 450}
        },
        {
            location = {x = 655, y = 625}
        },
        {
            location = {x = 372, y = 480}
        },
        {
            location = {x = 625, y = 320}
        },
    },
    firstMapLotteryNodePostions = cc.p(1210, 370),
    carnieThemeBasePath = 'carnieTheme/springAct_21',
    keepRepKey = {
        SUMMER_ACTIVITY_EGG_BG_BELOW         = true,
        SUMMER_ACTIVITY_EGG_BG_DRAW          = true,
        SUMMER_ACTIVITY_EGG_BG_EXTRA         = true,
        SUMMER_ACTIVITY_EGG_BG_NUM           = true,
        SUMMER_ACTIVITY_EGG_BG               = true,
        SUMMER_ACTIVITY_EGG_BTN_LIMITED      = true,
        SUMMER_ACTIVITY_EGG_BTN_ONE          = true,
        SUMMER_ACTIVITY_EGG_BTN_REWARDS      = true,
        SUMMER_ACTIVITY_EGG_BTN_TEN          = true,
        SUMMER_ACTIVITY_EGG_LABEL_DRAW       = true,
        SUMMER_ACTIVITY_EGG_LABEL_EXTRA      = true,
        SUMMER_ACTIVITY_EGG_LABEL_LIMITED    = true,
        SUMMER_ACTIVITY_EGGREWARDS_BG_CARD   = true,
        SPINE_ACTIVITY_NIUDANJI_PATH         = true,
        SUMMER_ACTIVITY_MAPS_ONE             = true,
        SUMMER_ACTIVITY_ICON_LAMP            = true,
        SPINE_ACTIVITY_DENGLONG_PATH         = true,
        SUMMER_ACTIVITY_ICO_POINT            = true,
        SPINE_ACTIVITY_JIQI_PATH             = true,
        SPINE_YLY_PATH                       = true,
        SPINE_ACTIVITY_YLY_PATH              = true,
        SUMMER_ACTIVITY_RANK_BG_QBOSS        = true,
        SUMMER_ACTIVITY_ENTRANCE_BG          = true,
        SUMMER_ACTIVITY_ENTRANCE_BTN_ENTER   = true,
        SUMMER_ACTIVITY_ENTRANCE_LABEL_TITLE = true,
        SUMMER_ACTIVITY_ENTRANCE_LIGHT       = true,
        SUMMER_ACTIVITY_RANK_BG_BOSS         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD_2       = true,
        SPINE_WUYA_PATH                      = true,
        SUMMER_ACTIVITY_DAN_PATH             = true,
        SUMMER_ACTIVITY_QBAN                 = true,
        SPINE_SKELETON_PATH                  = true,
    },
    audioConf = {
        FIRST_MAP  = {sheetName = AUDIOS.GHOST.name, cueName = AUDIOS.GHOST.Food_ghost_dancing.id},
        SECOND_MAP = {sheetName = AUDIOS.ALICE.name, cueName = AUDIOS.ALICE.Food_alice_dream.id},
    },
    getSecondMapBgByChapterId = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/springAct_21/map/bg/activity_summer_maps_100%s.jpg", chapterId or 1)
    end,
    getUnopenImg = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/springAct_21/map/icon/summer_activity_maps_icon_%s.jpg", chapterId or 1)
    end,
    hideStoryPos = cc.p(0, 0),
}
return podTable