local podTable = {
    po = {
        [__("Tips：每次击退了本章节的小丑后，章节内的关卡点都会刷新重置。")]             = __('每次击退了本章节的镜妖后，章节内的关卡点都会刷新重置。'),
        [__("游乐园很有趣的哦！\n别担心，我会一直在你身边保护你，所以一起来玩吧！")]       = __('沉寂的地下宫殿，需要一次新的探寻。'),
        [__("每个章节小丑伤害排行榜前%s名可获得：")]                                  = __('每个章节镜妖伤害排行榜前%s名可获得：'),
        [__("扭蛋机")]                                                           = __('机关蟹'),
        [__("在游乐园中战斗可获得的点数。击退小丑时，根据造成的伤害可以获得更多的点数哦。")] = __('在秋山中进行战斗可获得的点数。击退镜妖时，根据造成的伤害可以获得更多的点数哦。'),
        [__("恐怖游乐园")]                                                        = __('失落的雀羽'),
        [__("马戏团")]                                                           = __('古陵'),
        [__("拥有引路灯: %s")]                                                    = __('拥有古镜: %s'),
        [__("乐园排行榜")]                                                        = __('秋山排行榜'),
        [__("小丑伤害排行")]                                                      = __('镜妖伤害排行'),
        [__("本关卡无三星过关条件")]                                               = __('本关卡无三星过关条件'),
        [__("普通扭蛋")]                                                         = __('日常机关'),
        [__("游乐园点数")]                                                       = __('秋山点数'),
        [__("累计扭蛋奖励")]                                                      = __('累计转动次数奖励'),
        [__("扭10次")]                                                          = __('转动10次'),
        [__("扭1次")]                                                           = __('转动1次'),
        [__("您还没有参与游乐园的活动哦~")]                                         = __('您还没有参与秋山的活动哦'),
        [__("今日蛋池")]                                                         = __('今日机关蟹'),
        [__("扭蛋上新")]                                                         = __('机关上新'),
        [__("排行榜每小时更新一次排名")]                                           = __('排行榜每小时更新一次排名'),
        [__("特典扭蛋预告")]                                                     = __('特典预告'),
        [__("消耗1个引路灯直接找到小丑")]                                          = __('消耗1个古镜直接找到镜妖'),
        [__("剩余扭蛋")]                                                        = __('剩余转动机关次数'),
        [__("进入游乐园")]                                                       = __('进入秋山'),
        [__("今日特典扭蛋")]                                                     = __('今日特典'),
        [__("乐园游玩奖励")]                                                     = __('秋山游玩奖励'),
        [__("累计完成小丑关卡奖励")]                                              = __('累计完成镜妖关卡奖励'),
        [__('完成小丑关卡%s次可获得')]                                            = __('完成镜妖关卡%s次可获得'),
        [__("完成本关卡，根据所造成的伤害折算成游乐园点数，每1000点伤害为1点游乐园点数，不满1000不会计入。")] = __('完成本关卡，根据所造成的伤害折算成秋山点数，每1000点伤害为1点秋山点数，不满1000不会计入。'),
        [__("完成本关卡，可获得500点游乐园点数。")]                                 = __('完成本关卡，可获得500点秋山点数。'),
        [__("剩余扭蛋不足")]                                                     = __('剩余转动机关次数不足'),
        [__("堕神诱饵")]                                                        = __('堕神诱饵'),
        [__("引出小丑")]                                                        = __('引出镜妖'),
        [__("小丑出现了!")]                                                     = __('镜妖出现了'),
        [__('镜子迷宫第1名')]                                                   = __('南离印馆前10名'),
        [__('旋转茶杯第1名')]                                                   = __('枫林前10名'),
        [__('矿道飞车第1名')]                                                   = __('山庄前10名'),
        [__('鬼屋第1名')]                                                      = __('亭廊前10名'),
        [__('马戏团第1名')]                                                     = __('古陵前10名'),
        [__('在镜子迷宫内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在南离印馆内对镜妖的单次伤害最高的玩家可以获得。'),
        [__('在旋转茶杯内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在枫林内对镜妖的单次伤害最高的玩家可以获得。'),
        [__('在矿道飞车内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在山庄内对镜妖的单次伤害最高的玩家可以获得。'),
        [__('在鬼屋内对小丑的单次伤害最高的玩家可以获得。')]                         = __('在亭廊内对镜妖的单次伤害最高的玩家可以获得。'),
        [__('在马戏团内对小丑的单次伤害最高的玩家可以获得。')]                       = __('在古陵内对镜妖的单次伤害最高的玩家可以获得。'),
        [__('第1名的额外奖励: ')]                                               = __('前10名的额外奖励: '),
    },
    firstMapNodePostions = {
        {
            location = {x = 1230, y = 570}
        },
        {
            location = {x = 920, y = 450}
        },
        {
            location = {x = 715, y = 625}
        },
        {
            location = {x = 390, y = 480}
        },
        {
            location = {x = 620, y = 320}
        },
    },
    firstMapLotteryNodePostions = cc.p(1170, 330),
    carnieThemeBasePath = 'carnieTheme/schoolAct_20',
    keepRepKey = {
        SUMMER_ACTIVITY_EGG_BG_BELOW         = true,
        SUMMER_ACTIVITY_EGG_BG_DRAW          = true,
        SUMMER_ACTIVITY_EGG_BG_EXTRA         = true,
        SUMMER_ACTIVITY_EGG_BG_NUM           = true,
        SUMMER_ACTIVITY_EGG_BG               = true,
        SUMMER_ACTIVITY_EGG_BTN_LIMITED      = true,
        SUMMER_ACTIVITY_EGG_BTN_ONE          = true,
        SUMMER_ACTIVITY_EGG_BTN_REWARDS      = true,
        SUMMER_ACTIVITY_EGG_BTN_TEN          = true,
        SUMMER_ACTIVITY_EGG_LABEL_DRAW       = true,
        SUMMER_ACTIVITY_EGG_LABEL_EXTRA      = true,
        SUMMER_ACTIVITY_EGG_LABEL_LIMITED    = true,
        SUMMER_ACTIVITY_EGGREWARDS_BG_CARD   = true,
        SPINE_ACTIVITY_NIUDANJI_PATH         = true,
        SUMMER_ACTIVITY_MAPS_ONE             = true,
        SUMMER_ACTIVITY_ICON_LAMP            = true,
        SPINE_ACTIVITY_DENGLONG_PATH         = true,
        SUMMER_ACTIVITY_ICO_POINT            = true,
        SPINE_ACTIVITY_JIQI_PATH             = true,
        SPINE_YLY_PATH                       = true,
        SPINE_ACTIVITY_YLY_PATH              = true,
        SUMMER_ACTIVITY_RANK_BG_QBOSS        = true,
        SUMMER_ACTIVITY_ENTRANCE_BG          = true,
        SUMMER_ACTIVITY_ENTRANCE_BTN_ENTER   = true,
        SUMMER_ACTIVITY_ENTRANCE_LABEL_TITLE = true,
        SUMMER_ACTIVITY_ENTRANCE_LIGHT       = true,
        SUMMER_ACTIVITY_RANK_BG_BOSS         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD_2       = true,
        SPINE_WUYA_PATH                      = true,
        SUMMER_ACTIVITY_DAN_PATH             = true,
        SUMMER_ACTIVITY_QBAN                 = true,
        SPINE_SKELETON_PATH                  = true,
    },
    audioConf = {
        FIRST_MAP  = {sheetName = AUDIOS.WYS.name, cueName = AUDIOS.WYS.FOOD_WYS_GUILINGGAO_HAPPY.id},
        SECOND_MAP = {sheetName = AUDIOS.XNH.name, cueName = AUDIOS.XNH.FOOD_XNH_JIEDAO.id},
    },
    getSecondMapBgByChapterId = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/schoolAct_20/map/bg/activity_summer_maps_100%s.jpg", chapterId or 1)
    end,
    getUnopenImg = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/schoolAct_20/map/icon/summer_activity_maps_icon_%s.jpg", chapterId or 1)
    end,
    hideStoryPos = cc.p(0, 0),
}
return podTable