local podTable = {
    po = {
        [__("Tips：每次击退了本章节的小丑后，章节内的关卡点都会刷新重置。")]             = __('每次击退了本章节的鲷鱼刺身后，章节内的关卡点都会刷新重置。'),
        [__("游乐园很有趣的哦！\n别担心，我会一直在你身边保护你，所以一起来玩吧！")]       = __('无光森林中祭坛的秘密，等待众人挖掘。'),
        [__("每个章节小丑伤害排行榜前%s名可获得：")]                                  = __('每个章节鲷鱼刺身伤害排行榜前%s名可获得：'),
        [__("扭蛋机")]                                                           = __('召唤阵'),
        [__("在游乐园中战斗可获得的点数。击退小丑时，根据造成的伤害可以获得更多的点数哦。")] = __('在无光森林中进行战斗可获得的点数。击退鲷鱼刺身时，根据造成的伤害可以获得更多的点数哦。'),
        [__("恐怖游乐园")]                                                        = __('极光神境'),
        [__("马戏团")]                                                           = __('现世之门'),
        [__("拥有引路灯: %s")]                                                    = __('拥有占星仪: %s'),
        [__("乐园排行榜")]                                                        = __('无光森林排行榜'),
        [__("小丑伤害排行")]                                                      = __('鲷鱼刺身伤害排行'),
        [__("本关卡无三星过关条件")]                                               = __('本关卡无三星过关条件'),
        [__("普通扭蛋")]                                                         = __('日常召唤阵'),
        [__("游乐园点数")]                                                       = __('无光森林点数'),
        [__("累计扭蛋奖励")]                                                      = __('累计召唤次数奖励'),
        [__("扭10次")]                                                          = __('召唤10次'),
        [__("扭1次")]                                                           = __('召唤1次'),
        [__("您还没有参与游乐园的活动哦~")]                                         = __('您还没有参与无光森林的活动哦'),
        [__("今日蛋池")]                                                         = __('今日召唤阵'),
        [__("扭蛋上新")]                                                         = __('召唤阵上新'),
        [__("排行榜每小时更新一次排名")]                                           = __('排行榜每小时更新一次排名'),
        [__("特典扭蛋预告")]                                                     = __('特典预告'),
        [__("消耗1个引路灯直接找到小丑")]                                          = __('消耗1个占星仪直接找到鲷鱼刺身'),
        [__("剩余扭蛋")]                                                        = __('剩余召唤次数'),
        [__("进入游乐园")]                                                       = __('进入无光森林'),
        [__("今日特典扭蛋")]                                                     = __('今日特典'),
        [__("乐园游玩奖励")]                                                     = __('无光森林调查奖励'),
        [__("累计完成小丑关卡奖励")]                                              = __('累计完成鲷鱼刺身关卡奖励'),
        [__('完成小丑关卡%s次可获得')]                                            = __('完成鲷鱼刺身关卡%s次可获得'),
        [__("完成本关卡，根据所造成的伤害折算成游乐园点数，每1000点伤害为1点游乐园点数，不满1000不会计入。")] = __('完成本关卡，根据所造成的伤害折算成无光森林点数，每1000点伤害为1点无光森林点数，不满1000不会计入。'),
        [__("完成本关卡，可获得500点游乐园点数。")]                                 = __('完成本关卡，可获得500点无光森林点数。'),
        [__("剩余扭蛋不足")]                                                     = __('剩余召唤次数不足'),
        [__("堕神诱饵")]                                                        = __('散落星尘'),
        [__("引出小丑")]                                                        = __('引出鲷鱼刺身'),
        [__("小丑出现了!")]                                                     = __('鲷鱼刺身出现了'),
        [__('镜子迷宫第1名')]                                                   = __('无光森林前10名'),
        [__('旋转茶杯第1名')]                                                   = __('祭坛前10名'),
        [__('矿道飞车第1名')]                                                   = __('极光之庭前10名'),
        [__('鬼屋第1名')]                                                      = __('幻境歌舞町前10名'),
        [__('马戏团第1名')]                                                     = __('现世之门前10名'),
        [__('在镜子迷宫内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在无光森林内对鲷鱼刺身的单次伤害最高的玩家可以获得。'),
        [__('在旋转茶杯内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在祭坛内对鲷鱼刺身的单次伤害最高的玩家可以获得。'),
        [__('在矿道飞车内对小丑的单次伤害最高的玩家可以获得。')]                      = __('在极光之庭内对鲷鱼刺身的单次伤害最高的玩家可以获得。'),
        [__('在鬼屋内对小丑的单次伤害最高的玩家可以获得。')]                         = __('在幻境歌舞町内对鲷鱼刺身的单次伤害最高的玩家可以获得。'),
        [__('在马戏团内对小丑的单次伤害最高的玩家可以获得。')]                       = __('在现世之门内对鲷鱼刺身的单次伤害最高的玩家可以获得。'),
        [__('第1名的额外奖励: ')]                                               = __('前10名的额外奖励: '),
    },
    firstMapNodePostions = {
        {
            location = {x = 390, y = 440}
        },
        {
            location = {x = 670, y = 370}
        },
        {
            location = {x = 955, y = 310}
        },
        {
            location = {x = 830, y = 550}
        },
        {
            location = {x = 1300, y = 545}
        },
    },
    firstMapLotteryNodePostions = cc.p(1340, 370),
    carnieThemeBasePath = 'carnieTheme/japan_21',
    keepRepKey = {
        SUMMER_ACTIVITY_EGG_BG_BELOW         = true,
        SUMMER_ACTIVITY_EGG_BG_DRAW          = true,
        SUMMER_ACTIVITY_EGG_BG_EXTRA         = true,
        SUMMER_ACTIVITY_EGG_BG_NUM           = true,
        SUMMER_ACTIVITY_EGG_BG               = true,
        SUMMER_ACTIVITY_EGG_BTN_LIMITED      = true,
        SUMMER_ACTIVITY_EGG_BTN_ONE          = true,
        SUMMER_ACTIVITY_EGG_BTN_REWARDS      = true,
        SUMMER_ACTIVITY_EGG_BTN_TEN          = true,
        SUMMER_ACTIVITY_EGG_LABEL_DRAW       = true,
        SUMMER_ACTIVITY_EGG_LABEL_EXTRA      = true,
        SUMMER_ACTIVITY_EGG_LABEL_LIMITED    = true,
        SUMMER_ACTIVITY_EGGREWARDS_BG_CARD   = true,
        SPINE_ACTIVITY_NIUDANJI_PATH         = true,
        SUMMER_ACTIVITY_MAPS_ONE             = true,
        SUMMER_ACTIVITY_ICON_LAMP            = true,
        SPINE_ACTIVITY_DENGLONG_PATH         = true,
        SUMMER_ACTIVITY_ICO_POINT            = true,
        SPINE_ACTIVITY_JIQI_PATH             = true,
        SPINE_YLY_PATH                       = true,
        SPINE_ACTIVITY_YLY_PATH              = true,
        SUMMER_ACTIVITY_RANK_BG_QBOSS        = true,
        SUMMER_ACTIVITY_ENTRANCE_BG          = true,
        SUMMER_ACTIVITY_ENTRANCE_BTN_ENTER   = true,
        SUMMER_ACTIVITY_ENTRANCE_LABEL_TITLE = true,
        SUMMER_ACTIVITY_ENTRANCE_LIGHT       = true,
        SUMMER_ACTIVITY_RANK_BG_BOSS         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD         = true,
        SUMMER_ACTIVITY_RANK_BG_CARD_2       = true,
        SPINE_WUYA_PATH                      = true,
        SUMMER_ACTIVITY_DAN_PATH             = true,
        SUMMER_ACTIVITY_QBAN                 = true,
        SPINE_SKELETON_PATH                  = true,
    },
    audioConf = {
        FIRST_MAP  = {sheetName = AUDIOS.YLY.name, cueName = AUDIOS.YLY.FOOD_YLY_SAD.id},
        SECOND_MAP = {sheetName = AUDIOS.BWY.name, cueName = AUDIOS.BWY.FOOD_BWY_HUAZHAO.id},
    },
    getSecondMapBgByChapterId = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/japan_21/map/bg/activity_summer_maps_100%s.jpg", chapterId or 1)
    end,
    getUnopenImg = function(chapterId)
        return string.format("ui/home/activity/carnieTheme/japan_21/map/icon/summer_activity_maps_icon_%s.jpg", chapterId or 1)
    end,
    hideStoryPos = cc.p(0, 0),
}
return podTable