---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019/10/17 10:40 AM
---
local Anniversary19DreamCommonView = require("Game.views.anniversary19.Anniversary19DreamCommonView")
---@class Anniversary19LittleMonsterView : Anniversary19DreamCommonView
local Anniversary19LittleMonsterView = class('Anniversary19LittleMonsterView',Anniversary19DreamCommonView)
local anniversary2019Mgr = app.anniversary2019Mgr
function Anniversary19LittleMonsterView:AddDiffView(exploreModuleId , exploreId)
	local conf = anniversary2019Mgr:GetDreamQuestTypeConfByDreamQuestType(anniversary2019Mgr.dreamQuestType.LITTLE_MONSTER)
	local oneConf = conf[tostring(exploreModuleId)][tostring(exploreId)]
	local questId = oneConf.questId
	local parseConf = anniversary2019Mgr:GetConfigParse()
	local questConf = anniversary2019Mgr:GetConfigDataByName(parseConf.TYPE.QUEST)
	local showMonster = questConf[tostring(questId)].showMonster or {}
	local monsterId = showMonster[1] or 300150
	local monsterConf = CommonUtils.GetConfigAllMess('monster' , 'monster')
	local monsterOneConf = monsterConf[tostring(monsterId)]
	local skinId = monsterOneConf.skinId
	local qAvatar = AssetsUtils.GetCardSpineNode({skinId = skinId, scale = 1})
	qAvatar:setAnimation(0, 'idle', true)
	qAvatar:setPosition(cc.p(300, 50))
	self.viewData.centerLayout:addChild(qAvatar)
end

function Anniversary19LittleMonsterView:UpdateUI(exploreModuleId ,  exploreId , result)
	local rewardData = anniversary2019Mgr:GetDreamTypeReward(exploreModuleId ,anniversary2019Mgr.dreamQuestType.LITTLE_MONSTER , exploreId)
	local viewData = self.viewData
	display.commonLabelParams(viewData.resultLabel , {text = app.anniversary2019Mgr:GetPoText(__('战斗胜利可获得'))})
	display.commonLabelParams(viewData.descrLabel , {text  = app.anniversary2019Mgr:GetPoText(__('在梦境中遇到了神秘怪物，不知为何却感受到了敌意。')) , w = 300 , hAlign = display.TAC })
	display.commonLabelParams(viewData.titleBtn , {text = app.anniversary2019Mgr:GetPoText(__('战斗'))})
	viewData.goodNode:RefreshSelf(rewardData)
	self:SetRightCenterLayoutVisible(true)
	if result == 2 then
		self:UpdateFailureUI()
	else
		self:UpdateStartUI()
	end
end

function Anniversary19LittleMonsterView:UpdateFailureUI()
	local viewData = self.viewData
	self:SetTwoBtn()
	display.commonLabelParams(viewData.leftButton , fontWithColor(14 , {text = app.anniversary2019Mgr:GetPoText(__('放弃'))}))
	display.commonLabelParams(viewData.rightButton , fontWithColor(14 , {text = app.anniversary2019Mgr:GetPoText(__('挑战'))}))
end

function Anniversary19LittleMonsterView:UpdateStartUI()
	local viewData = self.viewData
	self:SetOnlyOneBtn()
	display.commonLabelParams(viewData.rightButton , fontWithColor(14 , {text = app.anniversary2019Mgr:GetPoText(__('挑战'))}))
end
return Anniversary19LittleMonsterView

