---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019/10/17 10:40 AM
---
local Anniversary19DreamCommonView = require("Game.views.anniversary19.Anniversary19DreamCommonView")
---@class Anniversary19QuestionView : Anniversary19DreamCommonView
local Anniversary19QuestionView = class('Anniversary19QuestionView',Anniversary19DreamCommonView)
function Anniversary19QuestionView:AddDiffView()
	local changeSkinData = app.anniversary2019Mgr:GetChangeSkinData()
	local skinId = changeSkinData.answerQuestSkinId or 251293 --251293
	local qAvatar = AssetsUtils.GetCardSpineNode({skinId = skinId , scale = 0.8})
	qAvatar:setAnimation(0, 'idle', true)
	qAvatar:setPosition(cc.p(350, 50))
	self.viewData.centerLayout:addChild(qAvatar)
end

function Anniversary19QuestionView:UpdateUI(exploreModuleId ,  exploreId )
	local anniversary2019Mgr = app.anniversary2019Mgr
	local rewardData = anniversary2019Mgr:GetDreamTypeReward(exploreModuleId ,anniversary2019Mgr.dreamQuestType.ANSWER_SHUT  , exploreId)
	local viewData = self.viewData
	display.commonLabelParams(viewData.resultLabel , {text = app.anniversary2019Mgr:GetPoText(__('回答正确可获得'))})
	display.commonLabelParams(viewData.descrLabel , {text  = app.anniversary2019Mgr:GetPoText(__('你的面前凭空出现了一个身影，看来总是随心所欲的柴郡猫想要向你询问些什么。'))  })
	display.commonLabelParams(viewData.titleBtn , {text = app.anniversary2019Mgr:GetPoText(__('柴郡猫'))})
	display.commonLabelParams(viewData.rightButton, fontWithColor(14, {text = app.anniversary2019Mgr:GetPoText(__('回答'))}))
	viewData.goodNode:RefreshSelf(rewardData)
	self:SetRightCenterLayoutVisible(true)
	self:SetOnlyOneBtn()
end
return Anniversary19QuestionView

