---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019/10/17 10:40 AM
---
local Anniversary19DreamCommonView = require("Game.views.anniversary19.Anniversary19DreamCommonView")
---@class Anniversary19ChestView : Anniversary19DreamCommonView
local Anniversary19ChestView = class('Anniversary19ChestView',Anniversary19DreamCommonView)
local anniversary2019Mgr = app.anniversary2019Mgr
function Anniversary19ChestView:AddDiffView()
	local chestPath = anniversary2019Mgr.spineTable.WONDERLAND_EXPLORE_BOX
	anniversary2019Mgr:AddSpineCacheByPath(chestPath)
	local  chestSpine = SpineCache(SpineCacheName.ANNIVERSARY_2019):createWithName(chestPath)
	chestSpine:setAnimation(0,"idle" , true )
	chestSpine:setPosition(300, 200)
	chestSpine:setAnchorPoint(display.center)
	local viewData = self.viewData
	viewData.centerLayout:addChild(chestSpine)
	viewData.centerLayout:setVisible(true)
	viewData.chestSpine = chestSpine
end

function Anniversary19ChestView:UpdateUI(exploreModuleId ,  exploreId )
	local anniversary2019Mgr = app.anniversary2019Mgr
	local rewardData = anniversary2019Mgr:GetDreamTypeReward(exploreModuleId ,anniversary2019Mgr.dreamQuestType.CHEST_SHUT , exploreId)
	local viewData = self.viewData
	display.commonLabelParams(viewData.resultLabel , {text = app.anniversary2019Mgr:GetPoText(__('打开宝箱可获得'))})
	display.commonLabelParams(viewData.descrLabel , {text  = app.anniversary2019Mgr:GetPoText(__('偶然发现了在路边的箱子，走近一看，居然没有上锁。\n要不要打开看一下呢？')) , w = 300 , hAlign = display.TAL })
	display.commonLabelParams(viewData.titleBtn , {text = app.anniversary2019Mgr:GetPoText(__('神秘的宝箱'))})
	display.commonLabelParams(viewData.rightButton, fontWithColor(14, {text = app.anniversary2019Mgr:GetPoText(__('打开'))}))
	viewData.goodNode:RefreshSelf(rewardData)
	self:SetRightCenterLayoutVisible(true)
	self:SetOnlyOneBtn()
end
return Anniversary19ChestView

