---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019/10/17 10:40 AM
---
local Anniversary19DreamCommonView = require("Game.views.anniversary19.Anniversary19DreamCommonView")
---@class Anniversary19TrapShutView : Anniversary19DreamCommonView
local Anniversary19TrapShutView = class('Anniversary19TrapShutView',Anniversary19DreamCommonView)
local anniversary2019Mgr = app.anniversary2019Mgr
function Anniversary19TrapShutView:AddDiffView(exploreModuleId)
	local bossSpine = anniversary2019Mgr.spineTable.WONDERLAND_EXPLORE_BOSS
	anniversary2019Mgr:AddSpineCacheByPath(bossSpine)
	local bossSpine = SpineCache(SpineCacheName.ANNIVERSARY_2019):createWithName(bossSpine)
	bossSpine:setAnimation(0,"play" .. exploreModuleId  , false )
	bossSpine:setPosition(300, 300)
	bossSpine:setAnchorPoint(display.center)
	local viewData = self.viewData
	viewData.centerLayout:addChild(bossSpine)
	viewData.centerLayout:setVisible(true)
	viewData.storySpine = bossSpine
end

function Anniversary19TrapShutView:UpdateUI(exploreModuleId ,  exploreId)
	local viewData = self.viewData
	display.commonLabelParams(viewData.descrLabel , {text  = app.anniversary2019Mgr:GetPoText(__('这里是现实还是梦境？看来还是得先打败了眼前的这个敌人才行。')) })
	display.commonLabelParams(viewData.titleBtn , {text = app.anniversary2019Mgr:GetPoText(__('发现目标'))})
	display.commonLabelParams(viewData.rightButton , fontWithColor(14 , {text = app.anniversary2019Mgr:GetPoText(__('确定'))}))
	self:SetRightCenterLayoutVisible(false)
	self:SetOnlyOneBtn()
end

return Anniversary19TrapShutView

