---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2018/8/7 8:46 PM
---
--[[
活动副本配表解析器
--]]
local AbstractBaseParser = require('Game.Datas.Parser')
---@class FishConfigParser
local FishConfigParser  = class('FishConfigParser', AbstractBaseParser)

FishConfigParser.NAME = 'FishConfigParser'

FishConfigParser.TYPE = {
    BUFF           = 'buff',
    LEVEL          = 'level',
    PARAM_CONFIG   = 'paramConfig',
    PRAY           = 'pray',
    MALL           = 'mall',
    PRAY_NUM       = 'prayNum',
    PRODUCE_CONFIG = 'produceConfig'
}

function FishConfigParser:ctor()
    self.super.ctor(self, table.values(FishConfigParser.TYPE))
end


return FishConfigParser