---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2018/9/18 11:56 AM
---
local RES_DICT = {
    CG_MAIN_LINE_1                = _res('ui/home/cg/CG_main_line_1.png'),
    CG_MAIN_FRAME_LOCK            = _res('ui/home/cg/CG_main_frame_lock.png'),
    CG_MAIN_FRAME_COMPLETED       = _res('ui/home/cg/CG_main_frame_completed.png'),
    CG_PUZZLE_BG_ITEM             = _res('ui/home/cg/CG_main_bg_card.png'),
    TEMP_CG_1                     = _res('ui/home/cg/completeCG/temp_cg_1.jpg'),
}
local CGCOnfig = CommonUtils.GetConfigAllMess('cg' ,'collection')
---@class CGCellView
local CGCellView = class('home.CGCellView',function ()
    local node = CLayout:create(cc.size(400 , 290))
    node.name = 'Game.views.CGCellView'
    node:enableNodeEvents()
    return node
end)

function CGCellView:ctor(param)
    param = param or {}
    self:initUI()
end
function CGCellView:initUI()
    local size =  cc.size(400, 290)
    local cellLayout = display.newLayer(687, 363,
            { ap = display.CENTER, color = cc.c4b(0 ,0,0, 0 ), size = cc.size(400, 290) ,enable =  true  })
    self:addChild(cellLayout)
    cellLayout:setPosition(size.width/2 , size.height/2 )

    local bottomImage = display.newImageView(RES_DICT.CG_PUZZLE_BG_ITEM, 206, 121,
            { ap = display.CENTER, tag = 6, enable = false, scale9 = true, size = cc.size(386, 244) })
    cellLayout:addChild(bottomImage)

    local prograssLabel = display.newLabel(20, 22,
            { ap = display.LEFT_CENTER, color = '#5b3c25', text = "", fontSize = 20, tag = 7 })
    cellLayout:addChild(prograssLabel)

    local cgNameLabel = display.newLabel(384, 22,
            { ap = display.RIGHT_CENTER, color = '#5b3c25', text = "", fontSize = 24, tag = 8 })
    cellLayout:addChild(cgNameLabel)

    local lineImage = display.newImageView(RES_DICT.CG_MAIN_LINE_1, 206, 38,
            { ap = display.CENTER, tag = 13, enable = false, scale9 = true, size = cc.size(365, 1) })
    cellLayout:addChild(lineImage)

    local cardFragmentLayout = display.newLayer(0, 48,
            { ap = display.LEFT_BOTTOM,  size = cc.size(391, 240), enable = true })
    cellLayout:addChild(cardFragmentLayout)

    local cgFragment = FilteredSpriteWithOne:create(RES_DICT.TEMP_CG_1)
    cgFragment:setAnchorPoint(display.CENTER)
    cgFragment:setPosition(cc.p(197, 118))
    --display.newImageView(RES_DICT.TEMP_CG_1, 197, 118,
    --        { ap = display.CENTER, tag = 14, enable = false })
    cardFragmentLayout:addChild(cgFragment)

    local cgFrame = display.newNSprite(RES_DICT.CG_MAIN_FRAME_COMPLETED, 197, 118,
            { ap = display.CENTER, tag = 15, size = cc.size(395, 247) })
    cardFragmentLayout:addChild(cgFrame)

    self.viewData =  {
        cellLayout              = cellLayout,
        bottomImage             = bottomImage,
        prograssLabel           = prograssLabel,
        cgNameLabel             = cgNameLabel,
        lineImage               = lineImage,
        cardFragmentLayout      = cardFragmentLayout,
        cgFragment              = cgFragment,
        cgFrame                 = cgFrame,
    }
end
--[[
　　---@Description: 刷新UI 显示
　　---@param :
　  ---@return :
　　---@author : xingweihao
　　---@date : 2018/9/18 1:26 PM
--]]
function CGCellView:RefresshUI(id , ownerNum , countNum )
    local viewData = self.viewData
    local cgOneConfig = CGCOnfig[tostring(id)] or {}
    local cgName = cgOneConfig.name  or ""
    local icon =   cgOneConfig.miniIcon
    local path  = _res( string.format("ui/home/cg/completeCG/%s.jpg" , icon or "loading_view_14_s" ))
    if not  utils.isExistent(path) then
        path =  _res( "ui/home/cg/completeCG/temp_cg_1.jpg" )
    end
    viewData.cgFragment:setTexture(path)
    --print(ownerNum , countNum)
    if checkint(ownerNum)  == checkint(countNum )  then
        viewData.cgFragment:clearFilter()
        viewData.cgFrame:setTexture(RES_DICT.CG_MAIN_FRAME_COMPLETED)
        viewData.prograssLabel:setVisible(false)
    else
        viewData.cgFragment:setFilter(GrayFilter:create())
        viewData.prograssLabel:setVisible(true)
        viewData.cgFrame:setTexture(RES_DICT.CG_MAIN_FRAME_LOCK)
        display.commonLabelParams(viewData.prograssLabel , {text = string.format("%d/%d" , checkint(ownerNum)  , checkint(countNum)  )})
    end
    display.commonLabelParams(viewData.cgNameLabel , {text = cgName})
    viewData.cellLayout:setTag(id)
end
return CGCellView