---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengjixian.
--- DateTime: 2018/10/22 3:51 PM
---
--[[
    燃战排行榜Mediator
--]]
local Mediator = mvc.Mediator

local SaiMoeRankMediator = class("SaiMoeRankMediator", Mediator)

local NAME = "SaiMoeRankMediator"

local shareFacade = AppFacade.GetInstance()
local uiMgr = app.uiMgr
local gameMgr = app.gameMgr
local function pairsByKeys(t)
    local a = {}
    for n in pairs(t) do
        a[#a + 1] = n
    end
    table.sort(a, function(a, b)
        return checkint(a) < checkint(b)
    end)
    local i = 0
    return function()
        i = i + 1
        return a[i], t[a[i]]
    end
end
function SaiMoeRankMediator:ctor( params, viewComponent )
    self.super:ctor(NAME,viewComponent)
    self.rankData = params or {} -- 所有排行数据

    self.rewardsDatas = {}
    self.rewardsDatas['1'] = CommonUtils.GetConfigAllMess('rankRewards', 'cardComparison')['1']
    local rewardsDatas = {}
    for i, v in pairsByKeys(CommonUtils.GetConfigAllMess('rankRewards', 'cardComparison')['2']) do
        rewardsDatas[tostring(table.nums(rewardsDatas)+1)] = v
    end
    self.rewardsDatas['2'] = rewardsDatas
    self.selectedRankType = 1
    self.selectedRank = self.rankData.supportGroupId or 1
end

function SaiMoeRankMediator:InterestSignals()
    local signals = {
        COUNT_DOWN_ACTION,
    }
    return signals
end

function SaiMoeRankMediator:ProcessSignal( signal )
    local name = signal:GetName()
    local body = checktable(signal:GetBody())
    if name == COUNT_DOWN_ACTION then
        local timerName = body.timerName
        if timerName == 'SAIMOE' then
            local leftSeconds = body.countdown
            self:UpdateCountDown( checkint(leftSeconds) )
        end
    end
end

function SaiMoeRankMediator:Initial( key )
    self.super.Initial(self,key)
    local scene = uiMgr:GetCurrentScene()
    local viewComponent  = require( 'Game.views.saimoe.SaiMoeRankView' ).new()
    self:SetViewComponent(viewComponent)
    viewComponent:setPosition(display.center)
    scene:AddDialog(viewComponent)
    viewComponent.viewData.backBtn:setOnClickScriptHandler(function ()
        PlayAudioByClickClose()
        shareFacade:UnRegsitMediator(NAME)
    end)
    viewComponent.viewData.rewardBtn:setOnClickScriptHandler(handler(self, self.RewardButtonCallback))
    viewComponent.viewData.gridView:setDataSourceAdapterScriptHandler(handler(self, self.RankDataSource))

    self:CreateTypeTabs()
    self:RankTypeButtonCallback(self.selectedRankType)

    self:UpdateCountDown( checkint(gameMgr:GetUserInfo().comparisonActivityTime) )
end

function SaiMoeRankMediator:UpdateCountDown( countdown )
    local viewData = self.viewComponent.viewData
    if countdown <= 0 then
        viewData.timeNum:setVisible(false)
        viewData.timeLabel:setString(__('已结束'))
        viewData.timeLabel:setVisible(true)
        --viewData.timeLabel:setPositionX(viewData.timeNum:getPositionX() + 10)
    else
        if checkint(countdown) <= 86400 then
            viewData.timeNum:setString(string.formattedTime(checkint(countdown),'%02i:%02i:%02i'))
            viewData.timeLabel:setVisible(false)
        else
            local day = math.floor(checkint(countdown)/86400)
            viewData.timeNum:setString(string.fmt('_day_',{_day_ = day}))
            viewData.timeLabel:setVisible(true)
            --viewData.timeLabel:setPositionX(viewData.timeNum:getPositionX() + viewData.timeNum:getContentSize().width + 10)
        end
    end
end

function SaiMoeRankMediator:RankDataSource( p_convertview, idx )
    local pCell = p_convertview
    local index = idx + 1
    local cSize = cc.size(1035, 112)

    if pCell == nil then
        pCell = require('home.RankSaiMoeCell').new(cSize)
    end
    xTry(function()
        local datas = self.rankListData[index]
        pCell.rankNum:setString(datas.rank)
        pCell.avatarIcon:RefreshSelf({level = datas.playerLevel, avatar = datas.playerAvatar, avatarFrame = datas.playerAvatarFrame})
        pCell.nameLabel:setString(datas.playerName)
        pCell.scoreNum:setString(datas.score)
        pCell.avatarIcon:setTag(index)
        pCell.avatarIcon:setOnClickScriptHandler(function ( sender )
            uiMgr:AddDialog('common.PlayerHeadPopup', {playerId = datas.playerId, type = CommonUtils.GetHeadPopupTypeByPlayerId(datas.playerId)})
        end)
        if pCell.scoreNum:getContentSize().width >= 200 then
            local scale = 200/pCell.scoreNum:getContentSize().width
            pCell.scoreNum:setScale(scale)
        end
        if checkint(datas.rank) >= 1 and checkint(datas.rank) <= 3 then
            pCell.rankBg:setVisible(true)
            pCell.rankBg:setTexture(_res('ui/home/rank/restaurant_info_bg_rank_num' .. tostring(datas.rank) .. '.png'))
        else
            pCell.rankBg:setVisible(false)
        end
    end,__G__TRACKBACK__)
    return pCell
end
--[[
查看奖励按钮点击回调
--]]
function SaiMoeRankMediator:RewardButtonCallback( sender )
    local scene = uiMgr:GetCurrentScene()
    local rewardsDatas
    local title = ''
    if 1 == self.selectedRankType then
        rewardsDatas = self.rewardsDatas[tostring(self.selectedRank)]
        title = __('票数排行榜奖励')
    else
        rewardsDatas = CommonUtils.GetConfigAllMess('rankDamageRewards', 'cardComparison')
        title = __('伤害排行榜奖励')
    end
    local LobbyRewardListView  = require( 'Game.views.LobbyRewardListView' ).new({tag = 1200, rewardsDatas = rewardsDatas, title = title})
    LobbyRewardListView:setTag(1200)
    LobbyRewardListView:setPosition(display.center)
    scene:AddDialog(LobbyRewardListView)
end
function SaiMoeRankMediator:CreateTypeTabs()
    local viewData = self:GetViewComponent().viewData
    viewData.expandableListView:removeAllExpandableNodes()
    local size = cc.size(212, 90)
    local expandableNode = require('home.RankSaiMoeTypeCell').new(size)
    expandableNode.buttonLayout:setOnClickScriptHandler(handler(self, self.RankTypeButtonCallback))
    display.commonLabelParams(expandableNode.nameLabel, {w = 170, hAlign= display.TAC ,text = __('应援票数榜')})
    viewData.expandableListView:insertExpandableNodeAtLast(expandableNode)
    expandableNode.arrowIcon:setVisible(true)
    expandableNode.buttonLayout:setTag(1)
    expandableNode:setExpanded(1 == self.selectedRankType)

    local playerConf = CommonUtils.GetConfigAllMess('comparisonInfo', 'cardComparison')
    for i = 1, 2 do
        local childSize = cc.size(size.width, 66)
        local childNode = CLayout:create()
        childNode:setContentSize(childSize)

        local eventNode = CLayout:create(childSize)
        eventNode:setPosition(utils.getLocalCenter(childNode))
        childNode:addChild(eventNode)

        local buttonImage = i == self.selectedRank and _res('ui/home/rank/rank_btn_2_select.png') or _res('ui/home/rank/rank_btn_2_default.png')
        local bgBtn = display.newButton(size.width * 0.5, 4,{
            n = buttonImage, ap = cc.p(0.5, 0)
        })
        eventNode:addChild(bgBtn)
        childNode.bgBtn = bgBtn

        bgBtn:setTag(i)
        bgBtn:setOnClickScriptHandler(handler(self, self.TabButtonCallback))
        display.commonLabelParams(bgBtn, fontWithColor(14, {text = playerConf[tostring(i)].message , reqW = 140}))
        expandableNode:insertItemNodeAtLast(childNode)
    end

    local expandableDamageNode = require('home.RankSaiMoeTypeCell').new(size)
    expandableDamageNode.buttonLayout:setOnClickScriptHandler(handler(self, self.RankTypeButtonCallback))
    expandableDamageNode.nameLabel:setString(__('最高伤害排行榜'))
    display.commonLabelParams(expandableDamageNode.nameLabel, {w = 170, hAlign= display.TAC ,text = __('最高伤害排行榜')})
    viewData.expandableListView:insertExpandableNodeAtLast(expandableDamageNode)
    expandableDamageNode.buttonLayout:setTag(2)

    viewData.expandableListView:reloadData()
end
function SaiMoeRankMediator:RankTypeButtonCallback( sender )
    if tolua.type(sender) == 'ccw.CButton' then
        PlayAudioByClickNormal()
    end
    local rankTypes = nil
    if type(sender) == 'number' then
        rankTypes = sender
    else
        rankTypes = sender:getTag()
        if rankTypes == self.selectedRankType then return end
    end
    self.selectedRankType = rankTypes
    local viewData = self:GetViewComponent().viewData
    for i = 1, 2 do
        local v = viewData.expandableListView:getExpandableNodeAtIndex(i-1)
        if i ~= self.selectedRankType then
            v.unselectedImg:setVisible(true)
            v.selectedImg:setVisible(false)
            v:setExpanded(false)
            if v.arrowIcon:isVisible() then
                v.arrowIcon:setRotation(270)
            end
        else
            v.unselectedImg:setVisible(false)
            v.selectedImg:setVisible(true)
            v:setExpanded(true)
            if v.arrowIcon:isVisible() then
                v.arrowIcon:setRotation(0)
            end
        end
    end
    if 1 == rankTypes then
        self:TabButtonCallback(checkint(self.selectedRank))
    else
        local viewData = self:GetViewComponent().viewData
        self.rankListData = self.rankData.damageRanks
        viewData.gridView:setCountOfCell(#self.rankListData)
        viewData.gridView:reloadData()
        self:ShowMyRank(self.rankData.myDamageRank, self.rankData.myDamageScore)
    end
    viewData.expandableListView:reloadData()
end
--[[
左侧页签点击回调
--]]
function SaiMoeRankMediator:TabButtonCallback( sender )
    if tolua.type(sender) == 'ccw.CButton' then
        PlayAudioByClickNormal()
    end
    local rankTypes = nil
    if type(sender) == 'number' then
        rankTypes = sender
    else
        rankTypes = sender:getTag()
        if rankTypes == self.selectedRank then return end
    end
    self.selectedRank = rankTypes
    local viewData = self:GetViewComponent().viewData
    local expandableNode = viewData.expandableListView:getExpandableNodeAtIndex(0)
    for i = 1, 2 do
        local childNode = expandableNode:getItemNodeAtIndex(i - 1)
        if i == rankTypes then
            childNode.bgBtn:setNormalImage(_res('ui/home/rank/rank_btn_2_select.png'))
            childNode.bgBtn:setSelectedImage(_res('ui/home/rank/rank_btn_2_select.png'))
        else
            childNode.bgBtn:setNormalImage(_res('ui/home/rank/rank_btn_2_default.png'))
            childNode.bgBtn:setSelectedImage(_res('ui/home/rank/rank_btn_2_default.png'))
        end
    end
    self.rankListData = self.rankData.ranks[tostring(self.selectedRank)]
    viewData.gridView:setCountOfCell(#self.rankListData)
    viewData.gridView:reloadData()

    if checkint(self.selectedRank) == checkint(self.rankData.supportGroupId) then
        self:ShowMyRank(self.rankData.mySupportRank, self.rankData.mySupportScore)
    else
        self:ShowMyRank()
    end
end

function SaiMoeRankMediator:ShowMyRank(myRank, myScore)
    local viewData = self:GetViewComponent().viewData

    local scoreNum = viewData.scoreNum
    local playerRankLabel = viewData.playerRankLabel
    local rankBg = viewData.rankBg
    local playerRankNum = viewData.playerRankNum
    if (not myRank and not myScore) or 0 == checkint(myRank) then
        playerRankLabel:setString(__('未入榜'))
        rankBg:setVisible(false)
        playerRankNum:setString('')
    else
        if checkint(myRank) >= 1 and checkint(myRank) <= 3 then
            rankBg:setVisible(true)
            rankBg:setTexture(_res('ui/home/rank/restaurant_info_bg_rank_num' .. tostring(myRank) .. '.png'))
        else
            rankBg:setVisible(false)
        end
        playerRankNum:setString(myRank)
        playerRankLabel:setString('')
    end
    scoreNum:setString(tostring(checkint(myScore)))
end

function SaiMoeRankMediator:OnRegist(  )
end

function SaiMoeRankMediator:OnUnRegist(  )
    local scene = uiMgr:GetCurrentScene()
    scene:RemoveDialog(self:GetViewComponent())
end

return SaiMoeRankMediator
