---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengjixian.
--- DateTime: 2018/10/18 4:35 PM
---
--[[
    燃战应援查看奖励界面
--]]
local GameScene = require( "Frame.GameScene" )
---@class SaiMoeRewardView :GameScene
local SaiMoeRewardView = class("SaiMoeRewardView", GameScene)
local shareFacade = AppFacade.GetInstance()
local gameMgr = shareFacade:GetManager("GameManager")
local uiMgr = shareFacade:GetManager("UIManager")

local RES_DICT          = {
    COMMON_BG_4                     = _res('ui/common/common_bg_4.png'),
    FRAME_SP                        = _res('ui/tastingTour/stage/fish_travel_point_bg_frame'),
    LABEL_SP                        = _res('ui/tastingTour/stage/fish_travel_point_label'),
    LINE_SP                         = _res('ui/tastingTour/stage/fish_travel_point_line'),
}

function SaiMoeRewardView:ctor( ... )
    GameScene.ctor(self, 'Game.views.saimoe.SaiMoeRewardView')
    self.args = unpack({...}) or {}

    self:InitUI()
end

function SaiMoeRewardView:InitUI()
    local eaterLayer = CColorView:create(cc.c4b(0, 0, 0, 180))
    eaterLayer:setTouchEnabled(true)
    eaterLayer:setContentSize(display.size)
    eaterLayer:setPosition(cc.p(display.cx, display.cy))
    self:addChild(eaterLayer, -1)
    eaterLayer:setOnClickScriptHandler(function(sender)
        shareFacade:UnRegsitMediator("SaiMoeRewardMediator")
    end)
    self.eaterLayer = eaterLayer

    local function CreateView()
        local view = CLayout:create(display.size)
        display.commonUIParams(view, {po = display.center})
        view:setName('SaiMoeRewardView')
        self:addChild(view)

        -----------------rewardView start-----------------
        local rewardView = display.newLayer(display.cx - 408, display.cy - 342,
                {
                    ap = display.LEFT_BOTTOM,
                    size = cc.size(816, 684),
                    enable = false,
                })
        view:addChild(rewardView)

        local BG = display.newImageView(RES_DICT.COMMON_BG_4, 408, 342,
                {
                    ap = display.CENTER,
                    scale9 = true, size = cc.size(816, 684),
                    enable = true
                })
        rewardView:addChild(BG)

        local curLabel = display.newLabel(26, 619,
                {
                    text = __('当前应援：'),
                    ap = display.LEFT_CENTER,
                    fontSize = 24,
                    color = '#5b3c25',
                })
        rewardView:addChild(curLabel)
        local curLabelSize = display.getLabelContentSize(curLabel)
        local supportNumLabel = display.newLabel(26 + curLabelSize.width, 619,
                {
                    text = '',
                    ap = display.LEFT_CENTER,
                    fontSize = 26,
                    color = '#ffdf75',
                    font = TTF_GAME_FONT, ttf = true,
                    outline = '#774013',
                })
        rewardView:addChild(supportNumLabel)

        local tipLabel = display.newLabel(787, 619,
                {
                    text = __('达成条件即可获得'),
                    ap = display.RIGHT_CENTER,
                    fontSize = 24,
                    color = '#5b3c25',
                })
        rewardView:addChild(tipLabel)

        local listSize = cc.size(816,570)
        local listCellSize = cc.size(listSize.width, 110)
        local rewardList = CGridView:create(listSize)
        rewardList:setSizeOfCell(listCellSize)
        rewardList:setColumns(1)
        rewardList:setAutoRelocate(true)
        rewardList:setAnchorPoint(display.LEFT_BOTTOM)
        rewardList:setPosition(cc.p(0, 10))
        rewardView:addChild(rewardList)

        ------------------rewardView end------------------

        local xx = display.cx
        local yy = display.cy - rewardView:getContentSize().height / 2 - 14
        local closeLabel = display.newButton(xx,yy,{
            n = _res('ui/common/common_bg_close.png'),-- common_click_back
        })
        closeLabel:setEnabled(false)
        display.commonLabelParams(closeLabel,{fontSize = 18,text = __('点击空白处关闭')})
        self:addChild(closeLabel, 10)

        return {
            view                    = view,
            rewardView              = rewardView,
            BG                      = BG,
            curLabel                = curLabel,
            supportNumLabel         = supportNumLabel,
            tipLabel                = tipLabel,
            rewardList              = rewardList,
        }
    end
    xTry(function ( )
        self.viewData = CreateView()
        self:show()
    end, __G__TRACKBACK__)
end

function SaiMoeRewardView:show()
    self.eaterLayer:setOpacity(0)
    self.viewData.view:setScaleY(0)

    local actionTime = 0.15
    self:runAction(cc.Sequence:create({
        cc.Spawn:create({
            cc.TargetedAction:create(self.eaterLayer, cc.FadeTo:create(actionTime, 180)),
            cc.TargetedAction:create(self.viewData.view, cc.ScaleTo:create(actionTime, 1))
        })
    }))
end

--[[
    创建第一个Cell
--]]
function SaiMoeRewardView:CreateOneCell(data)
    data = data or {}
    local point = data.num
    local frameImage = display.newImageView(RES_DICT.FRAME_SP, 0, 0, {scale9 = true, size = cc.size(790, 104)})
    local frameImageSize = frameImage:getContentSize()
    frameImageSize = cc.size(frameImageSize.width + 26, frameImageSize.height + 5)
    local frameLayout = display.newLayer(frameImageSize.width/2 ,frameImageSize.height/2 ,
            {ap = display.CENTER , size = frameImageSize , color1 = cc.r4b()} )
    frameImage:setPosition(cc.p(frameImageSize.width/2 , frameImageSize.height/2))
    frameLayout:addChild(frameImage)

    -- 添加icon

    local leftSize = cc.size(150, 95)
    -- 左侧的叙述
    local offset = 5
    local leftLayout = display.newLayer(35 , frameImageSize.height/2  , { ap = display.LEFT_CENTER , color1 = cc.r4b()  , size = leftSize})
    local label = display.newLabel(0, leftSize.height - 15 -offset, fontWithColor('10' , {color = "#8c6648" ,  ap = display.LEFT_CENTER , text = __('应援达到')}))
    leftLayout:addChild(label)



    local spLine = display.newImageView(RES_DICT.LINE_SP , 0,leftSize.height - 28 -offset  , { ap = display.LEFT_CENTER})
    leftLayout:addChild(spLine)
    frameLayout:addChild(leftLayout)


    local  labelSp = display.newImageView(RES_DICT.LABEL_SP , 0,leftSize.height - 47 - offset  , { ap = display.LEFT_CENTER})
    leftLayout:addChild(labelSp)

    local starPoint = display.newLabel(5, leftSize.height - 47-offset , fontWithColor('14' , { fontSize = 22, color = "#fff3cc" , outline = "#774013" ,   ap = display.LEFT_CENTER , text = point}))
    leftLayout:addChild(starPoint)
    local rewardLabel = display.newLabel(0, leftSize.height - 80-offset , fontWithColor('10' , { color = "#786d6d", ap = display.LEFT_CENTER , text = __('可获得:')}))
    leftLayout:addChild(rewardLabel)
    local reward = data.rewards or {}
    local goodSize = cc.size(95,100)
    local goodsIcons = {}
    for i, v in pairs(reward) do
        local goodsIcon = require('common.GoodNode').new({id = reward[i].goodsId, amount = reward[i].num, showAmount = true })
        goodsIcon:setAnchorPoint(display.CENTER)
        goodsIcon:setPosition(cc.p(frameImageSize.width / 2 - (#reward-1)*goodSize.width/2 + (i-1)*goodSize.width, frameImageSize.height/2 ))
        frameLayout:addChild(goodsIcon)
        goodsIcon:setScale(0.8)
        goodsIcon:setTag(reward[i].goodsId)
        display.commonUIParams(goodsIcon, {animate = false, cb = function (sender)
            PlayAudioByClickNormal()
            uiMgr:ShowInformationTipsBoard({targetNode = sender, iconId = sender:getTag(), type = 1})
        end})
        table.insert(goodsIcons, goodsIcon)
    end

    local rewardBtn = display.newButton(frameImageSize.width - 30 , frameImageSize.height/2 ,
            {
                ap = display.RIGHT_CENTER ,
                n =_res('ui/common/common_btn_orange') ,
                scale9 = true

            })
    rewardBtn:setTag(checkint(data.id))
    display.commonLabelParams(rewardBtn, fontWithColor('14' ,{ text = __('领取')}) )
    frameLayout:addChild(rewardBtn)
    local cellLayout = CGridViewCell:new()
    cellLayout:setContentSize(self.viewData.rewardList:getSizeOfCell())
    cellLayout:addChild(frameLayout)
    frameLayout:setPosition(cc.p(frameImageSize.width/2 ,frameImageSize.height/2))

    cellLayout.viewData = {
        frameLayout = frameLayout ,
        frameImageSize = frameImageSize,
        rewardBtn   = rewardBtn ,
        starPoint   = starPoint,
        goodsIcons  = goodsIcons,
    }
    return cellLayout
end

return SaiMoeRewardView