---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2018/8/7 8:34 PM
---
--[[
餐厅信息知名度view
--]]
---@class FishingPopularityView
local FishingPopularityView = class('FishingPopularityView', function ()
    local node = CLayout:create(cc.size(753, 556))
    node:setAnchorPoint(cc.p(0, 0))
    node.name = 'home.FishingPopularityView'
    node:enableNodeEvents()
    return node
end)
local RES_DICR = {
    BG_TEXT      = _res('ui/common/commcon_bg_text.png'),
    BTN_TIPS     = _res('ui/common/common_btn_tips.png'),
    BG_AWARENESS = _res('ui/home/lobby/information/restaurant_info_bg_awareness.png'),
    TITLE_5      = _res('ui/common/common_title_5.png'),
    BAR_EXP_1    = _res('ui/home/lobby/information/restaurant_bar_exp_1.png'),
    BAR_EXP_2    = _res('ui/home/lobby/information/setup_bar_exp_2.png'),
    BTN_ORANGE   = _res('ui/common/common_btn_orange.png'),
    NO_PET       = _res('ui/common/common_tips_no_pet.png'),
}
local function CreateView( )
    local size = cc.size(753, 556)
    local view = CLayout:create(size)
    local bg = display.newImageView(RES_DICR.BG_TEXT , 0, 8, {ap = cc.p(0, 0), scale9 = true, size = cc.size(753, 546)})
    view:addChild(bg)
    local tipsIcon = display.newButton(25, 526, {n = RES_DICR.BTN_TIPS})
    view:addChild(tipsIcon, 10)
    local rankLabel = display.newRichLabel(50, 526, { ap  = display.LEFT_CENTER ,   c = {fontWithColor(6, {text = __('当前钓场规模：'), ap = cc.p(0, 0.5)})} })
    view:addChild(rankLabel, 10)
    local function CreateBg( x, y, title )
        local layout = CLayout:create(cc.size(753, 186))
        layout:setPosition(cc.p(x, y))
        local bg = display.newImageView(RES_DICR.BG_AWARENESS, 0, 0, {ap = cc.p(0, 0), scale9 = true, size = cc.size(753, 186)})
        layout:addChild(bg)
        local titleBg = display.newButton(layout:getContentSize().width/2, 158, {n = RES_DICR.TITLE_5, enable = false})
        layout:addChild(titleBg)
        display.commonLabelParams(titleBg, fontWithColor(4, {text = title}))
        return layout
    end
    -- 知名度
    local popularityBg = CreateBg(size.width/2, 406, __('人气度'))
    view:addChild(popularityBg, 5)
    local tipsLabel = display.newLabel(size.width/2, 108, fontWithColor(6, {text = __('tips：提升钓场等级可解锁新的钓手位置，提高钓场可设置的钓饵上限。'), w = 700}))
    popularityBg:addChild(tipsLabel, 5)
    --local popularityLabel = display.newLabel(100, 50, fontWithColor(4, {text = __('钓场人气度')}))
    --popularityBg:addChild(popularityLabel)
    local expProgressBar = CProgressBar:create(RES_DICR.BAR_EXP_1)
    expProgressBar:setBackgroundImage(RES_DICR.BAR_EXP_2)
    expProgressBar:setDirection(eProgressBarDirectionLeftToRight)
    expProgressBar:setAnchorPoint(cc.p(0.5, 0.5))
    expProgressBar:setPosition(cc.p(popularityBg:getContentSize().width/2 , 50))
    popularityBg:addChild(expProgressBar, 10)
    local expLabel = display.newLabel(popularityBg:getContentSize().width/2 + 40, 50, fontWithColor(9, {text = ''}))
    popularityBg:addChild(expLabel, 10)
    local popularityIcon = display.newImageView(_res(CommonUtils.GetGoodsIconPathById(FISH_POPULARITY_ID)), 15, 50, {ap = cc.p(0, 0.5) , enable = true })
    popularityBg:addChild(popularityIcon, 10)
    popularityIcon:setScale(0.3)
    -- 升级材料
    local materialBg = CreateBg(size.width/2, 218, __('升级材料'))
    view:addChild(materialBg, 5)
    -- 升级按钮
    local upgradeBtn = display.newButton(size.width/2, 70, {n = RES_DICR.BTN_ORANGE})
    upgradeBtn:setTag(RemindTag.BTN_FISH_UPGRADE)
    view:addChild(upgradeBtn, 10)
    display.commonLabelParams(upgradeBtn, fontWithColor(14, {text = __('升级')}))
    local costLabel = display.newRichLabel(size.width/2, 10,
            {ap = cc.p(0.5, 0)})
    view:addChild(costLabel, 10)
    return {
        view 			 = view,
        upgradeBtn       = upgradeBtn,
        rankLabel		 = rankLabel,
        expProgressBar	 = expProgressBar,
        materialBg	     = materialBg,
        expLabel		 = expLabel,
        costLabel		 = costLabel,
        popularityIcon   = popularityIcon,
        tipsIcon         = tipsIcon ,
        popularityBg     = popularityBg
    }
end

function FishingPopularityView:ctor( ... )
    self.viewData_ = CreateView()
    self:addChild(self.viewData_.view, 1)
    self.viewData_.view:setPosition(utils.getLocalCenter(self))
end

return FishingPopularityView
