---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2018/10/12 3:27 PM
---
---@class AnniversalSelectPrceView
local AniversarySelectPriceView = class('AniversarySelectPriceView', function ()
    local node = CLayout:create(display.size)
    node.name = 'Game.views.artifact.AniversarySelectPriceView'
    node:setName('AniversarySelectPriceView')
    node:enableNodeEvents()
    return node
end)

local commonLabelParams = display.commonLabelParams
local newImageView = display.newImageView
local newLabel = display.newLabel
local newNSprite = display.newNSprite
local newButton = display.newButton
local newLayer = display.newLayer
local RES_DICT = {
    MARKET_SOLD_BG_GOODS_INFO     = app.anniversaryMgr:GetResPath('ui/home/commonShop/market_sold_bg_goods_info.png'),
    GOODS_ICON_195080             = app.anniversaryMgr:GetResPath('arts/goods/goods_icon_195080.png'),
    COOKING_BAR_1                 = app.anniversaryMgr:GetResPath('ui/home/kitchen/cooking_bar_1.png'),
    MARKET_BUY_BG_INFO            = app.anniversaryMgr:GetResPath('ui/home/market/market_buy_bg_info.png'),
    COMMON_BTN_TIPS_2             = app.anniversaryMgr:GetResPath('ui/common/common_btn_tips_2.png'),
    COMMON_BTN_ORANGE             = app.anniversaryMgr:GetResPath('ui/common/common_btn_orange.png'),
    MARKET_SOLD_BTN_SUB           = app.anniversaryMgr:GetResPath('ui/home/market/market_sold_btn_sub.png'),
    ANNI_STALL_FOODS_BG           = app.anniversaryMgr:GetResPath('ui/anniversary/anni_stall_foods_bg.png'),
    ANNI_STALL_FOODS_SELECT       = app.anniversaryMgr:GetResPath('ui/anniversary/anni_stall_foods_select.png'),
    COOKING_GRADE_ICO_5           = app.anniversaryMgr:GetResPath('ui/home/kitchen/cooking_grade_ico_5.png'),
    KITCHEN_BG_FOOD_QUAN          = app.anniversaryMgr:GetResPath('ui/home/kitchen/kitchen_bg_food_quan.png'),
    COMMON_BG_GOODS               = app.anniversaryMgr:GetResPath('ui/common/common_bg_goods.png'),
    MARKET_SOLD_BTN_PLUS          = app.anniversaryMgr:GetResPath('ui/home/market/market_sold_btn_plus.png'),
    COOKING_BAR_2                 = app.anniversaryMgr:GetResPath('ui/home/kitchen/cooking_bar_2.png'),
    ANNI_STALL_FOODS_DETAILS      = app.anniversaryMgr:GetResPath('ui/anniversary/anni_stall_foods_details.png'),
    COOKING_GRADE_ICO_1           = app.anniversaryMgr:GetResPath('ui/home/kitchen/cooking_grade_ico_1.png'),
}

function AniversarySelectPriceView:ctor( ... )
    ---@type TitlePanelBg
    local tiltleBgPanl = require('common.TitlePanelBg').new({ title = app.anniversaryMgr:GetPoText(__('添加食物')), type = 5 })
    tiltleBgPanl:setPosition(display.center)
    self:addChild(tiltleBgPanl)
    local view = tiltleBgPanl.viewData.view
    tiltleBgPanl.viewData.closeBtn:setVisible(false)
    local contentLayer = newLayer(25, 10,
                                  { ap = display.LEFT_BOTTOM, size = cc.size(1083, 580) })
    view:addChild(contentLayer,10)

    local rightLayout = newLayer(570, 2,
                                 { ap = display.LEFT_BOTTOM, size = cc.size(515, 578) })
    contentLayer:addChild(rightLayout)

    local bgImage = newImageView(RES_DICT.MARKET_BUY_BG_INFO, 0, 0,
                                 { ap = display.LEFT_BOTTOM, tag = 77, enable = false, scale9 = true, size = cc.size(510, 577) })
    rightLayout:addChild(bgImage)

    local bgImageTwo = newImageView(RES_DICT.ANNI_STALL_FOODS_DETAILS, 5, 295,
                                    { ap = display.LEFT_BOTTOM, tag = 78, enable = false })
    rightLayout:addChild(bgImageTwo)

    local tipButton = newButton( 461, 531,{ ap = display.CENTER, tag = 79 , n = RES_DICT.COMMON_BTN_TIPS_2} )
    tipButton:setScale(1, 1)
    rightLayout:addChild(tipButton)

    local circleImage = newNSprite(RES_DICT.KITCHEN_BG_FOOD_QUAN, 255, 426,
                                   { ap = display.CENTER, tag = 80 })
    circleImage:setScale(0.8, 0.8)
    rightLayout:addChild(circleImage)

    local prograssBarImage = newNSprite(RES_DICT.COOKING_BAR_2, 256, 327,
                                        { ap = display.CENTER, tag = 82 })
    prograssBarImage:setScale(1, 1)
    rightLayout:addChild(prograssBarImage)

    local gradeImage = newNSprite(RES_DICT.COOKING_GRADE_ICO_5, 147, 330,
                                  { ap = display.CENTER, tag = 81 })
    gradeImage:setScale(1, 1)
    rightLayout:addChild(gradeImage)

    local prograss = CProgressBar:create(RES_DICT.COOKING_BAR_1)
    prograss:setAnchorPoint(cc.p(0.5, 0.5))
    --prograss:setMaxValue(100)
    prograss:setPosition(256, 327)
    prograss:setValue(10)
    prograss:setScale(1, 1)
    prograss:setDirection(eProgressBarDirectionLeftToRight)
    rightLayout:addChild(prograss)

    local selectPrice = newNSprite(RES_DICT.MARKET_BUY_BG_INFO, 253, 221,
                                   { ap = display.CENTER, tag = 94 })
    selectPrice:setScale(1, 1)
    rightLayout:addChild(selectPrice)


    local goodInfo = newImageView(RES_DICT.MARKET_SOLD_BG_GOODS_INFO, 250, 122,
                                  { ap = display.CENTER, tag = 85, enable = true  })
    rightLayout:addChild(goodInfo)
    local goodInfoSize = goodInfo:getContentSize()
    local richLabel = display.newRichLabel(goodInfoSize.width/2 , goodInfoSize.height/2 , { r= true ,
        c = {
             fontWithColor(14 , { text = "1001" , color = '#d23d3d', fontSize = 30 }),
             {img = CommonUtils.GetGoodsIconPathById(GOLD_ID) , scale = 0.2}
        }
    })
    goodInfo:setContentSize(cc.size(150,49))
    goodInfo:addChild(richLabel)

    local addBtn = newButton(332 + 20, 122, { ap = display.CENTER ,  n = RES_DICT.MARKET_SOLD_BTN_PLUS, s = RES_DICT.MARKET_SOLD_BTN_PLUS, scale9 = true, size = cc.size(52, 53), tag = 86 })
    commonLabelParams(addBtn, fontWithColor(14, { text = "", fontSize = 24, color = '#414146' }))
    rightLayout:addChild(addBtn)

    local reduceBtn = newButton(174-20, 122, { ap = display.CENTER ,  n = RES_DICT.MARKET_SOLD_BTN_SUB, s = RES_DICT.MARKET_SOLD_BTN_SUB, scale9 = true, size = cc.size(52, 53), tag = 87 })
    commonLabelParams(reduceBtn, fontWithColor(14, { text = "", fontSize = 24, color = '#414146' }))
    rightLayout:addChild(reduceBtn)

    local recipeName = newLabel(254, 529,
                                { ap = display.CENTER, color = '#a04949', text = "xxxxx", fontSize = 24, tag = 86 })
    rightLayout:addChild(recipeName)

    local prograssValue = newLabel(254, 326,
                                   { ap = display.CENTER, color = '#ffffff', text = "10/10", fontSize = 24, tag = 87 })
    rightLayout:addChild(prograssValue)

    local successRateLabel = newLabel(254, 256,
                                    fontWithColor( 16, { ap = display.CENTER,text = app.anniversaryMgr:GetPoText(__('销售成功率')), fontSize = 24, tag = 88 }))
    rightLayout:addChild(successRateLabel,2)

    local successRateNumLabel = newLabel(254, 223,
                                         fontWithColor(14,{ outline = false , ap = display.CENTER, color = '#d23d3d', text = "100%", fontSize = 24, tag = 89 }))
    rightLayout:addChild(successRateNumLabel)

    local priceLabel = newLabel(254, 170,
                                { ap = display.CENTER, color = '#ffffff', text = "", fontSize = 24, tag = 90 })
    rightLayout:addChild(priceLabel)

    local putAwayBtn = newButton(256, 42, { ap = display.CENTER ,  n = RES_DICT.COMMON_BTN_ORANGE, s = RES_DICT.COMMON_BTN_ORANGE, enable = true  })
    commonLabelParams(putAwayBtn, fontWithColor(14, { text = app.anniversaryMgr:GetPoText(__('上架')), fontSize = 24 }))
    rightLayout:addChild(putAwayBtn)

    local recipeImage = newNSprite(RES_DICT.GOODS_ICON_195080, 251, 439,
                                   { ap = display.CENTER, tag = 88 })
    recipeImage:setScale(1, 1)
    rightLayout:addChild(recipeImage)

    local leftPanel = newLayer(2, 1,
                               { ap = display.LEFT_BOTTOM, size = cc.size(564, 578) })
    contentLayer:addChild(leftPanel)

    local bgImage_1 = newImageView(RES_DICT.COMMON_BG_GOODS, 281, 290,
                                   { ap = display.CENTER, tag = 77, enable = false, scale9 = true, size = cc.size(559, 573) })
    leftPanel:addChild(bgImage_1)

    local grideVIew =  CGridView:create(cc.size(561,568) )
    --grideVIew:setDirection(eScrollViewDirectionHorizontal)
    grideVIew:setSizeOfCell( cc.size(186, 186))
    grideVIew:setAnchorPoint( 0.500000 , 0.5)
    grideVIew:setColumns(3)
    grideVIew:setCountOfCell(20)
    grideVIew:setAutoRelocate(true)
    leftPanel:addChild(grideVIew)
    grideVIew:setDataSourceAdapterScriptHandler(handler(self,self.OnDataSource))
    grideVIew:setPosition(280 ,290)
    self.viewData =  {
        contentLayer            = contentLayer,
        rightLayout             = rightLayout,
        bgImage                 = bgImage,
        bgImageTwo              = bgImageTwo,
        tipButton               = tipButton,
        circleImage             = circleImage,
        prograssBarImage        = prograssBarImage,
        gradeImage              = gradeImage,
        prograss                = prograss,
        selectPrice             = selectPrice,
        goodInfo                = goodInfo,
        addBtn                  = addBtn,
        reduceBtn               = reduceBtn,
        recipeName              = recipeName,
        richLabel               = richLabel ,
        prograssValue           = prograssValue,
        successRateLabel        = successRateLabel,
        successRateNumLabel     = successRateNumLabel,
        priceLabel              = priceLabel,
        putAwayBtn              = putAwayBtn,
        recipeImage             = recipeImage,
        leftPanel               = leftPanel,
        bgImage_1               = bgImage_1,
        grideVIew               = grideVIew,
        closeView               = tiltleBgPanl.viewData.eaterLayer
    }

end
function AniversarySelectPriceView:CreateGridViewCell()
    local gridViewCell = CGridViewCell:new()
    local gridViewCellSize =  cc.size(186, 186)
    gridViewCell:setContentSize(gridViewCellSize)
    local cellLayout = newLayer(0, 0,
                                { ap = display.LEFT_BOTTOM, color = cc.c4b(0,0,0,0), size = gridViewCellSize, enable = true })

    gridViewCell:addChild(cellLayout)
    local bgCellImage = newImageView(RES_DICT.ANNI_STALL_FOODS_BG, 93, 93,
                                     { ap = display.CENTER, tag = 80, enable = false })
    cellLayout:addChild(bgCellImage)

    local lightImage = newImageView(RES_DICT.ANNI_STALL_FOODS_SELECT, 93, 93,
                                    { ap = display.CENTER, tag = 79, enable = false })
    cellLayout:addChild(lightImage)

    local recipeImage = newNSprite(RES_DICT.GOODS_ICON_195080, 93, 93,
                                     { ap = display.CENTER, tag = 82 })
    recipeImage:setScale(1, 1)
    cellLayout:addChild(recipeImage)

    local gradeImage = newNSprite(RES_DICT.COOKING_GRADE_ICO_1, 30, 152,
                                    { ap = display.CENTER, tag = 83 })
    gradeImage:setScale(1, 1)
    cellLayout:addChild(gradeImage)
    gridViewCell.viewData = {
        cellLayout = cellLayout,
        bgCellImage = bgCellImage,
        lightImage  = lightImage,
        recipeImage = recipeImage,
        gradeImage  = gradeImage
    }
    return gridViewCell
end
return AniversarySelectPriceView
