---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2018/10/12 3:27 PM
---
---@class AnniversaryFoodStoreView
local AnniversaryFoodStoreView = class('AnniversaryFoodStoreView', function ()
    local node = CLayout:create(display.size)
    node.name = 'Game.views.artifact.AnniversaryFoodStoreView'
    node:setName('AnniversaryFoodStoreView')
    node:enableNodeEvents()
    return node
end)
local newImageView = display.newImageView
local newLabel = display.newLabel
local newNSprite = display.newNSprite
local newLayer = display.newLayer
local GoodPurchaseNode = require('common.GoodPurchaseNode')
local RES_DICT = {
    COMMON_BTN_TIPS                 = app.anniversaryMgr:GetResPath('ui/common/common_btn_tips.png'),
    MAIN_BG_MONEY                   = app.anniversaryMgr:GetResPath('ui/home/nmain/main_bg_money.png'),
    COMMON_TITLE                    = app.anniversaryMgr:GetResPath('ui/common/common_title.png'),
    GOODS_ICON_121001               = app.anniversaryMgr:GetResPath('arts/goods/goods_icon_121001.png'),
    ANNI_MAPS_FOODS_SHOP_TASK       = app.anniversaryMgr:GetResPath('ui/anniversary/map/anni_maps_foods_shop_task.png'),
    COMMON_BTN_BACK                 = app.anniversaryMgr:GetResPath('ui/common/common_btn_back.png'),
    ROLE_13                         = app.anniversaryMgr:GetResPath('arts/roles/role_13.png'),
    MATERIAL_CARD_LABEL_RELEASETIME = app.anniversaryMgr:GetResPath('ui/home/materialScript/material_card_label_releasetime.png'),
    SHOP_BTN_GOODS_DEFAULT          = app.anniversaryMgr:GetResPath('ui/home/commonShop/shop_btn_goods_default.png'),
    SHIP_ICO_LABEL_GOODS_TAG        = app.anniversaryMgr:GetResPath('ui/airship/ship_ico_label_goods_tag.png'),
    ANNI_MAPS_SHOP_LINE           = app.anniversaryMgr:GetResPath('ui/anniversary/map/anni_maps_shop_line.png'),

}
function AnniversaryFoodStoreView:ctor( ... )
    local view = newLayer(display.cx, display.cy,{ap = display.CENTER, size = display.size})
    self:addChild(view)
    local swallowLayer = newLayer(667, 375,
                                  { ap = display.CENTER, color = cc.c4b(0,0,0,175), size = cc.size(display.width, display.height), enable = true })
    swallowLayer:setPosition(display.cx + 0, display.cy + 0)
    view:addChild(swallowLayer)

    local backBtn = display.newButton( 58, 697,
   { ap = display.CENTER, tag = 161 , n = RES_DICT.COMMON_BTN_BACK, s = RES_DICT.COMMON_BTN_BACK })
    backBtn:setScale(1, 1)
    backBtn:setPosition(display.SAFE_L + 58, display.height + -55)
    view:addChild(backBtn)

    local contentLayer = newLayer(667, 309,
                                  { ap = display.CENTER, size = cc.size(1200, 600) })
    contentLayer:setPosition(display.cx + 0, display.cy + -66)
    view:addChild(contentLayer)

    local rolePath = RES_DICT.ROLE_13
    local changeSkinTable = app.anniversaryMgr.changeSkinTable
    if changeSkinTable and changeSkinTable.shopRole then
        rolePath = app.anniversaryMgr:GetResPath('arts/roles/' .. tostring(changeSkinTable.shopRole))
    end
    local roleImage = newImageView(rolePath, 555, -25,
                                   { ap = display.CENTER, tag = 185, enable = false })
    contentLayer:addChild(roleImage)

    local shopTaskImage = newNSprite(RES_DICT.ANNI_MAPS_FOODS_SHOP_TASK, 572, 52,
                                     { ap = display.CENTER, tag = 125 })
    shopTaskImage:setScale(1, 1)
    contentLayer:addChild(shopTaskImage)

    local titleImage = newImageView(RES_DICT.MATERIAL_CARD_LABEL_RELEASETIME, 591, 34,
                                    { ap = display.CENTER, tag = 153, enable = false })
    contentLayer:addChild(titleImage)

    local requirementLabel = newLabel(591, 34,
                                      { ap = display.CENTER, color = '#ffffff', text = app.anniversaryMgr:GetPoText(__('只能选择一种购买')), fontSize = 22, tag = 152 })
    contentLayer:addChild(requirementLabel)


    local tabNameLabel = display.newButton(97, 744, { ap = display.LEFT_TOP ,  n = RES_DICT.COMMON_TITLE, d = RES_DICT.COMMON_TITLE, s = RES_DICT.COMMON_TITLE, scale9 = true, size = cc.size(303, 78) })
    display.commonLabelParams(tabNameLabel, {text = "", fontSize = 14, color = '#414146'})
    tabNameLabel:setPosition(display.cx + -570, display.height + -6)
    view:addChild(tabNameLabel ,101)

    local moduleName = display.newLabel(118, 30,
                                        fontWithColor('14' , { outline = false ,  ap = display.CENTER, color = '#5b3c25', text = app.anniversaryMgr:GetPoText(__('食谱商店')), reqW = 190 ,   fontSize = 30, tag = 71 }))
    tabNameLabel:addChild(moduleName)

    local tipButton = display.newNSprite(RES_DICT.COMMON_BTN_TIPS, 237, 30,
                                         { ap = display.CENTER, tag = 72 })
    tipButton:setScale(1, 1)
    tabNameLabel:addChild(tipButton)
    local buyLayouts = {}
    local posXtable = { 250, 550, 850 }
    for i = 1 ,  3 do
        local node = self:CreateBuyLayout()
        contentLayer:addChild(node)
        node:setPosition(posXtable[i] + 50 , 250 )
        buyLayouts[#buyLayouts+1] = node
    end
    local topLayoutSize = cc.size(display.width, 80)
    local moneyNodeLayout = CLayout:create(topLayoutSize)
    moneyNodeLayout:setName('TOP_LAYOUT')
    display.commonUIParams(moneyNodeLayout, {ap = display.CENTER_TOP, po = cc.p(display.cx, display.height)})
    self:addChild(moneyNodeLayout, GameSceneTag.Dialog_GameSceneTag)

    -- top icon
    local imageImage = display.newImageView(RES_DICT.MAIN_BG_MONEY,0, 0, {enable = false,
                                                                          scale9 = true, size = cc.size(680 + (display.width - display.SAFE_R), 54)})
    display.commonUIParams(imageImage,{ap = cc.p(1.0,1.0), po = cc.p(display.width,80)})
    moneyNodeLayout:addChild(imageImage)

    local moneyNods = {}
    local iconData = {app.anniversaryMgr:GetIncomeCurrencyID(), app.anniversaryMgr:GetAnniversaryTicketID(),DIAMOND_ID}
    for i,v in ipairs(iconData) do
        local purchaseNode = GoodPurchaseNode.new({id = v})
        purchaseNode:updataUi(checkint(v))
        display.commonUIParams(purchaseNode,
                               {ap = cc.p(1, 0.5), po = cc.p(topLayoutSize.width - 30 - (( 3 - i) * (purchaseNode:getContentSize().width + 16)), imageImage:getPositionY()- 26)})
        moneyNodeLayout:addChild(purchaseNode, 5)
        purchaseNode:setName('purchaseNode' .. i)
        purchaseNode.viewData.touchBg:setTag(checkint(v))
        moneyNods[tostring( v )] = purchaseNode
    end

    self.viewData =  {
        swallowLayer            = swallowLayer,
        backBtn                 = backBtn,
        contentLayer            = contentLayer,
        moneyNods               = moneyNods,
        roleImage               = roleImage,
        shopTaskImage           = shopTaskImage,
        titleImage              = titleImage,
        requirementLabel        = requirementLabel,
        tabNameLabel            = tabNameLabel ,
        buyLayouts              = buyLayouts ,
    }
end
function AnniversaryFoodStoreView:CreateBuyLayout()
    local buyLayoutOne = newLayer(0, 0 ,
                                  { ap = display.CENTER , size = cc.size(199, 248) , enable = true  })

    local shopImage = newImageView(RES_DICT.SHOP_BTN_GOODS_DEFAULT, 99, 124 ,
                                 { ap = display.CENTER, tag = 126 ,enable = true  })
    shopImage:setScale(1, 1)
    buyLayoutOne:addChild(shopImage)
    shopImage:setName("shopImage")

    local recipeName = newLabel(99.5, 100,
                                fontWithColor('14', { ap = display.CENTER, outline = false, ttf = true, font = TTF_GAME_FONT, color = '#5b3c25', fontSize = 24, text = "好好", tag = 128 }))
    buyLayoutOne:addChild(recipeName)
    recipeName:setName("recipeName")

    local lineImage = newNSprite(RES_DICT.ANNI_MAPS_SHOP_LINE, 99.5,  83,
                                 { ap = display.CENTER, tag = 165 })
    lineImage:setScale(1, 1)
    buyLayoutOne:addChild(lineImage)


    local expValueLabel = newLabel(99.5, 70,
                                  fontWithColor('10', { ap = display.CENTER, outline = false, color = '#5b3c25', fontSize = 24, text = "xxx", tag = 128 }))
    buyLayoutOne:addChild(expValueLabel)
    expValueLabel:setName("expValueLabel")
    local goodsBgImage = newImageView(RES_DICT.SHIP_ICO_LABEL_GOODS_TAG, 99, 163 + 10 ,
                                      { ap = display.CENTER, tag = 129, enable = false })
    buyLayoutOne:addChild(goodsBgImage)

    local recipeImage = newImageView(RES_DICT.GOODS_ICON_121001, 99, 162 + 10,
                                     { ap = display.CENTER, tag = 138, enable = false })
    buyLayoutOne:addChild(recipeImage)

    recipeImage:setName("recipeImage")
    recipeImage:setScale(0.6)

    local amoutRichLabel = display.newRichLabel(199/2 ,10 , { r= true ,  c = {
        fontWithColor('14' , {text = 200 }),
        {img = CommonUtils.GetGoodsIconPathById(DIAMOND_ID) , scale = 0.2 }
    }})
    buyLayoutOne:addChild(amoutRichLabel)
    amoutRichLabel:setName("amoutRichLabel")

    if isElexSdk() or isKoreanSdk() or isJapanSdk() then
        amoutRichLabel:setPositionY(8)
    end

    return buyLayoutOne
end
--[[
    刷新顶部的UI
--]]
function AnniversaryFoodStoreView:UpdateCountUI()
    if self.viewData and  self.viewData.moneyNods then
        for k ,v in pairs(self.viewData.moneyNods or {})do
            v:updataUi(checkint(k))
        end
    end
end
return AnniversaryFoodStoreView
