---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xingweihao.
--- DateTime: 2019/10/17 10:40 AM
---
local Anniversary20DreamCommonView = require("Game.views.anniversary20.Anniversary20DreamCommonView")
---@class Anniversary20QuestionView : Anniversary20DreamCommonView
local Anniversary20QuestionView = class('Anniversary20QuestionView',Anniversary20DreamCommonView)
function Anniversary20QuestionView:AddDiffView()
	local skinId = 252750
	local qAvatar = AssetsUtils.GetCardSpineNode({skinId = skinId , scale = 0.8})
	qAvatar:setAnimation(0, 'idle', true)
	qAvatar:setPosition(cc.p(250, 50))
	self.viewData.centerLayout:addChild(qAvatar)
end

function Anniversary20QuestionView:UpdateUI(mapGridId)
	local ANNIV2020 = FOOD.ANNIV2020
	local refId = app.anniv2020Mgr:getExploreingMapRefIdAt(mapGridId)
	local optionOneConf =  ANNIV2020.EXPLORE_TYPE_CONF[ANNIV2020.EXPLORE_TYPE.OPTION]:GetValue(refId)
	local rewardData = optionOneConf.rewards or {}
	local viewData = self.viewData
	display.commonLabelParams(viewData.resultLabel , {text = __('回答正确可获得')})
	display.commonLabelParams(viewData.descrLabel , {text  = __('神秘的魔法使叫住了你。\n「回答我的问题吧！如果答对了，我会赠你一件魔法的礼物。」')  })
	display.commonLabelParams(viewData.titleBtn , {text = __('魔法使的考验')})
	display.commonLabelParams(viewData.rightButton, fontWithColor(14, {text = __('回答')}))
	self:AddGoodNodes(rewardData)
	self:SetRightCenterLayoutVisible(true)
	self:SetOnlyOneBtn()
end

return Anniversary20QuestionView

